/*
 * ========================LICENSE_START=================================
 * 
 * Copyright (C) 2025 Regione Piemonte
 * 
 * SPDX-FileCopyrightText: (C) Copyright 2025 Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
export enum TipoEventoEnum {
  INS_ISTANZA = 'INS_ISTANZA',
  FIRMA_MOD = 'FIRMA_MOD',
  PRESENTA_MOD = 'PRESENTA_MOD',
  DA_FIRMARE = 'DA_FIRMARE',
  RICH_ALLEG = 'RICH_ALLEG',
  INT_ALL = 'INT_ALL',
  RIFIUTA = 'RIFIUTA',
  PROT_IST = 'PROT_IST',
  IN_CARICO = 'IN_CARICO',
  AVVIO = 'AVVIO',
  // NOTA_OTR = 'NOTA_OTR',
  PUBBLICA = 'PUBBLICA',
  // PROV_FINALE = 'PROV_FINALE',
  // PROT_INT = 'PROT_INT',
  // PUBBLICA_AVVISO = 'PUBBLICA_AVVISO',
  CONCL_BO = 'CONCL_BO',
  CORREGGI = 'CORREGGI',
  INS_PRATICA_BO = 'INS_PRATICA_BO',
  // INS_OSS = 'INS_OSS',
  PERF_ISTANZA = 'PERF_ISTANZA',
  PERF_ALLEGATI = 'PERF_ALLEGATI',
  COMPL_PERF_ALLEGATI = 'COMPL_PERF_ALLEGATI',
  RIC_INTEGR_SUCC = 'RIC_INTEGR_SUCC',
  COMPL_INTEGR_SUCC = 'COMPL_INTEGR_SUCC',
  RIC_SOSPENSIONE = 'RIC_SOSPENSIONE',
  COMPL_PERF_ISTANZA = 'COMPL_PERF_ISTANZA',
  ASSEGNATA = 'ASSEGNATA',
  DA_ASSEGNARE = 'DA_ASSEGNARE',
  DA_ASSEGNARE_UNICO = 'DA_ASSEGNARE_UNICO',
  SOSP_PROC = 'SOSP_PROC',
  UPD_CONTATTO_UTENTE = 'UPD_CONTATTO_UTENTE',
  INS_ALL_INTEGR = 'INS_ALL_INTEGR',
  SCARICA_ELEN_INTEG = 'SCARICA_ELEN_INTEG',
  SCARICATA_LETTERA = 'SCARICATA_LETTERA',
  FIRMATA_LETTERA = 'FIRMATA_LETTERA',
  ANNULLA_PERFALLEGATI = 'ANNULLA_PERFALLEGATI',
  ANNULLA_RICH_INTEGR = 'ANNULLA_RICH_INTEGR',
  ANNULLA_RIC_INT_SUCC = 'ANNULLA_RIC_INT_SUCC',
  INS_DOC_ISTR = 'INS_DOC_ISTR',
}
