/*-
 * ========================LICENSE_START=================================
 * 
 * Copyright (C) 2025 Regione Piemonte
 * 
 * SPDX-FileCopyrightText: (C) Copyright 2025 Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/*
 * cosmo-servizi-fruitori-xp
 * API esposte da Cosmo per l'integrazione con i fruitori esterni
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.csi.scriva.scrivabesrv.business.be.helper.cosmo.dto;

import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * AggiornaEventoFruitoreResponse
 */
public class AggiornaEventoFruitoreResponse {
  private String messaggio = null;

  public AggiornaEventoFruitoreResponse messaggio(String messaggio) {
    this.messaggio = messaggio;
    return this;
  }

   /**
   * Get messaggio
   * @return messaggio
  **/
  @ApiModelProperty(required = true, value = "")
  public String getMessaggio() {
    return messaggio;
  }

  public void setMessaggio(String messaggio) {
    this.messaggio = messaggio;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AggiornaEventoFruitoreResponse aggiornaEventoFruitoreResponse = (AggiornaEventoFruitoreResponse) o;
    return Objects.equals(this.messaggio, aggiornaEventoFruitoreResponse.messaggio);
  }

  @Override
  public int hashCode() {
    return Objects.hash(messaggio);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AggiornaEventoFruitoreResponse {\n");

    sb.append("    messaggio: ").append(toIndentedString(messaggio)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}