/*-
 * ========================LICENSE_START=================================
 * 
 * Copyright (C) 2025 Regione Piemonte
 * 
 * SPDX-FileCopyrightText: (C) Copyright 2025 Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/*
 * cosmo-servizi-fruitori-xp
 * API esposte da Cosmo per l'integrazione con i fruitori esterni
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.csi.scriva.scrivabesrv.business.be.helper.cosmo.dto;

import io.swagger.annotations.ApiModelProperty;

import java.time.OffsetDateTime;
import java.util.Objects;

/**
 * AggiornaEventoFruitoreRequest
 */
public class AggiornaEventoFruitoreRequest {
    private String codiceIpaEnte = null;

    private OffsetDateTime nuovaDataScadenza = null;

    private String nuovoTitolo = null;

    private String nuovaDescrizione = null;

    private Boolean eseguito = null;

    public AggiornaEventoFruitoreRequest codiceIpaEnte(String codiceIpaEnte) {
        this.codiceIpaEnte = codiceIpaEnte;
        return this;
    }

    /**
     * Get codiceIpaEnte
     *
     * @return codiceIpaEnte
     **/
    @ApiModelProperty(required = true, value = "")
    public String getCodiceIpaEnte() {
        return codiceIpaEnte;
    }

    public void setCodiceIpaEnte(String codiceIpaEnte) {
        this.codiceIpaEnte = codiceIpaEnte;
    }

    public AggiornaEventoFruitoreRequest nuovaDataScadenza(OffsetDateTime nuovaDataScadenza) {
        this.nuovaDataScadenza = nuovaDataScadenza;
        return this;
    }

    /**
     * Get nuovaDataScadenza
     *
     * @return nuovaDataScadenza
     **/
    @ApiModelProperty(value = "")
    public OffsetDateTime getNuovaDataScadenza() {
        return nuovaDataScadenza;
    }

    public void setNuovaDataScadenza(OffsetDateTime nuovaDataScadenza) {
        this.nuovaDataScadenza = nuovaDataScadenza;
    }

    public AggiornaEventoFruitoreRequest nuovoTitolo(String nuovoTitolo) {
        this.nuovoTitolo = nuovoTitolo;
        return this;
    }

    /**
     * Get nuovoTitolo
     *
     * @return nuovoTitolo
     **/
    @ApiModelProperty(value = "")
    public String getNuovoTitolo() {
        return nuovoTitolo;
    }

    public void setNuovoTitolo(String nuovoTitolo) {
        this.nuovoTitolo = nuovoTitolo;
    }

    public AggiornaEventoFruitoreRequest nuovaDescrizione(String nuovaDescrizione) {
        this.nuovaDescrizione = nuovaDescrizione;
        return this;
    }

    /**
     * Get nuovaDescrizione
     *
     * @return nuovaDescrizione
     **/
    @ApiModelProperty(value = "")
    public String getNuovaDescrizione() {
        return nuovaDescrizione;
    }

    public void setNuovaDescrizione(String nuovaDescrizione) {
        this.nuovaDescrizione = nuovaDescrizione;
    }

    public AggiornaEventoFruitoreRequest eseguito(Boolean eseguito) {
        this.eseguito = eseguito;
        return this;
    }

    /**
     * Get eseguito
     *
     * @return eseguito
     **/
    @ApiModelProperty(value = "")
    public Boolean isEseguito() {
        return eseguito;
    }

    public void setEseguito(Boolean eseguito) {
        this.eseguito = eseguito;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        AggiornaEventoFruitoreRequest aggiornaEventoFruitoreRequest = (AggiornaEventoFruitoreRequest) o;
        return Objects.equals(this.codiceIpaEnte, aggiornaEventoFruitoreRequest.codiceIpaEnte) &&
                Objects.equals(this.nuovaDataScadenza, aggiornaEventoFruitoreRequest.nuovaDataScadenza) &&
                Objects.equals(this.nuovoTitolo, aggiornaEventoFruitoreRequest.nuovoTitolo) &&
                Objects.equals(this.nuovaDescrizione, aggiornaEventoFruitoreRequest.nuovaDescrizione) &&
                Objects.equals(this.eseguito, aggiornaEventoFruitoreRequest.eseguito);
    }

    @Override
    public int hashCode() {
        return Objects.hash(codiceIpaEnte, nuovaDataScadenza, nuovoTitolo, nuovaDescrizione, eseguito);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class AggiornaEventoFruitoreRequest {\n");

        sb.append("    codiceIpaEnte: ").append(toIndentedString(codiceIpaEnte)).append("\n");
        sb.append("    nuovaDataScadenza: ").append(toIndentedString(nuovaDataScadenza)).append("\n");
        sb.append("    nuovoTitolo: ").append(toIndentedString(nuovoTitolo)).append("\n");
        sb.append("    nuovaDescrizione: ").append(toIndentedString(nuovaDescrizione)).append("\n");
        sb.append("    eseguito: ").append(toIndentedString(eseguito)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}