/*-
 * ========================LICENSE_START=================================
 * 
 * Copyright (C) 2025 Regione Piemonte
 * 
 * SPDX-FileCopyrightText: (C) Copyright 2025 Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/*
 * cosmo-servizi-fruitori-xp
 * API esposte da Cosmo per l'integrazione con i fruitori esterni
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.csi.scriva.scrivabesrv.business.be.helper.cosmo.dto;

import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * AvviaProcessoFruitoreResponse
 */
public class AvviaProcessoFruitoreResponse {
    private String idProcesso = null;

    private Integer idPraticaCosmo = null;

    private String idPratica = null;

    private String codiceIpaEnte = null;

    public AvviaProcessoFruitoreResponse idProcesso(String idProcesso) {
        this.idProcesso = idProcesso;
        return this;
    }

    /**
     * Get idProcesso
     *
     * @return idProcesso
     **/
    @ApiModelProperty(required = true, value = "")
    public String getIdProcesso() {
        return idProcesso;
    }

    public void setIdProcesso(String idProcesso) {
        this.idProcesso = idProcesso;
    }

    public AvviaProcessoFruitoreResponse idPraticaCosmo(Integer idPraticaCosmo) {
        this.idPraticaCosmo = idPraticaCosmo;
        return this;
    }

    /**
     * Get idPraticaCosmo
     *
     * @return idPraticaCosmo
     **/
    @ApiModelProperty(required = true, value = "")
    public Integer getIdPraticaCosmo() {
        return idPraticaCosmo;
    }

    public void setIdPraticaCosmo(Integer idPraticaCosmo) {
        this.idPraticaCosmo = idPraticaCosmo;
    }

    public AvviaProcessoFruitoreResponse idPratica(String idPratica) {
        this.idPratica = idPratica;
        return this;
    }

    /**
     * Get idPratica
     *
     * @return idPratica
     **/
    @ApiModelProperty(required = true, value = "")
    public String getIdPratica() {
        return idPratica;
    }

    public void setIdPratica(String idPratica) {
        this.idPratica = idPratica;
    }

    public AvviaProcessoFruitoreResponse codiceIpaEnte(String codiceIpaEnte) {
        this.codiceIpaEnte = codiceIpaEnte;
        return this;
    }

    /**
     * Get codiceIpaEnte
     *
     * @return codiceIpaEnte
     **/
    @ApiModelProperty(required = true, value = "")
    public String getCodiceIpaEnte() {
        return codiceIpaEnte;
    }

    public void setCodiceIpaEnte(String codiceIpaEnte) {
        this.codiceIpaEnte = codiceIpaEnte;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        AvviaProcessoFruitoreResponse avviaProcessoFruitoreResponse = (AvviaProcessoFruitoreResponse) o;
        return Objects.equals(this.idProcesso, avviaProcessoFruitoreResponse.idProcesso) &&
                Objects.equals(this.idPraticaCosmo, avviaProcessoFruitoreResponse.idPraticaCosmo) &&
                Objects.equals(this.idPratica, avviaProcessoFruitoreResponse.idPratica) &&
                Objects.equals(this.codiceIpaEnte, avviaProcessoFruitoreResponse.codiceIpaEnte);
    }

    @Override
    public int hashCode() {
        return Objects.hash(idProcesso, idPraticaCosmo, idPratica, codiceIpaEnte);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class AvviaProcessoFruitoreResponse {\n");

        sb.append("    idProcesso: ").append(toIndentedString(idProcesso)).append("\n");
        sb.append("    idPraticaCosmo: ").append(toIndentedString(idPraticaCosmo)).append("\n");
        sb.append("    idPratica: ").append(toIndentedString(idPratica)).append("\n");
        sb.append("    codiceIpaEnte: ").append(toIndentedString(codiceIpaEnte)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}