/*-
 * ========================LICENSE_START=================================
 * 
 * Copyright (C) 2025 Regione Piemonte
 * 
 * SPDX-FileCopyrightText: (C) Copyright 2025 Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/*
 * cosmo-servizi-fruitori-xp
 * API esposte da Cosmo per l'integrazione con i fruitori esterni
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.csi.scriva.scrivabesrv.business.be.helper.cosmo.dto;

import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * CreaPraticaFruitoreRequest
 */
public class CreaPraticaFruitoreRequest {
    private String idPratica = null;

    private String codiceIpaEnte = null;

    private String codiceTipologia = null;

    private String oggetto = null;

    private String riassunto = null;

    private String utenteCreazionePratica = null;

    private String metadati = null;

    public CreaPraticaFruitoreRequest idPratica(String idPratica) {
        this.idPratica = idPratica;
        return this;
    }

    /**
     * Get idPratica
     *
     * @return idPratica
     **/
    @ApiModelProperty(required = true, value = "")
    public String getIdPratica() {
        return idPratica;
    }

    public void setIdPratica(String idPratica) {
        this.idPratica = idPratica;
    }

    public CreaPraticaFruitoreRequest codiceIpaEnte(String codiceIpaEnte) {
        this.codiceIpaEnte = codiceIpaEnte;
        return this;
    }

    /**
     * Get codiceIpaEnte
     *
     * @return codiceIpaEnte
     **/
    @ApiModelProperty(required = true, value = "")
    public String getCodiceIpaEnte() {
        return codiceIpaEnte;
    }

    public void setCodiceIpaEnte(String codiceIpaEnte) {
        this.codiceIpaEnte = codiceIpaEnte;
    }

    public CreaPraticaFruitoreRequest codiceTipologia(String codiceTipologia) {
        this.codiceTipologia = codiceTipologia;
        return this;
    }

    /**
     * Get codiceTipologia
     *
     * @return codiceTipologia
     **/
    @ApiModelProperty(required = true, value = "")
    public String getCodiceTipologia() {
        return codiceTipologia;
    }

    public void setCodiceTipologia(String codiceTipologia) {
        this.codiceTipologia = codiceTipologia;
    }

    public CreaPraticaFruitoreRequest oggetto(String oggetto) {
        this.oggetto = oggetto;
        return this;
    }

    /**
     * Get oggetto
     *
     * @return oggetto
     **/
    @ApiModelProperty(required = true, value = "")
    public String getOggetto() {
        return oggetto;
    }

    public void setOggetto(String oggetto) {
        this.oggetto = oggetto;
    }

    public CreaPraticaFruitoreRequest riassunto(String riassunto) {
        this.riassunto = riassunto;
        return this;
    }

    /**
     * Get riassunto
     *
     * @return riassunto
     **/
    @ApiModelProperty(value = "")
    public String getRiassunto() {
        return riassunto;
    }

    public void setRiassunto(String riassunto) {
        this.riassunto = riassunto;
    }

    public CreaPraticaFruitoreRequest utenteCreazionePratica(String utenteCreazionePratica) {
        this.utenteCreazionePratica = utenteCreazionePratica;
        return this;
    }

    /**
     * Get utenteCreazionePratica
     *
     * @return utenteCreazionePratica
     **/
    @ApiModelProperty(value = "")
    public String getUtenteCreazionePratica() {
        return utenteCreazionePratica;
    }

    public void setUtenteCreazionePratica(String utenteCreazionePratica) {
        this.utenteCreazionePratica = utenteCreazionePratica;
    }

    public CreaPraticaFruitoreRequest metadati(String metadati) {
        this.metadati = metadati;
        return this;
    }

    /**
     * Get metadati
     *
     * @return metadati
     **/
    @ApiModelProperty(value = "")
    public String getMetadati() {
        return metadati;
    }

    public void setMetadati(String metadati) {
        this.metadati = metadati;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CreaPraticaFruitoreRequest creaPraticaFruitoreRequest = (CreaPraticaFruitoreRequest) o;
        return Objects.equals(this.idPratica, creaPraticaFruitoreRequest.idPratica) &&
                Objects.equals(this.codiceIpaEnte, creaPraticaFruitoreRequest.codiceIpaEnte) &&
                Objects.equals(this.codiceTipologia, creaPraticaFruitoreRequest.codiceTipologia) &&
                Objects.equals(this.oggetto, creaPraticaFruitoreRequest.oggetto) &&
                Objects.equals(this.riassunto, creaPraticaFruitoreRequest.riassunto) &&
                Objects.equals(this.utenteCreazionePratica, creaPraticaFruitoreRequest.utenteCreazionePratica) &&
                Objects.equals(this.metadati, creaPraticaFruitoreRequest.metadati);
    }

    @Override
    public int hashCode() {
        return Objects.hash(idPratica, codiceIpaEnte, codiceTipologia, oggetto, riassunto, utenteCreazionePratica, metadati);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class CreaPraticaFruitoreRequest {\n");

        sb.append("    idPratica: ").append(toIndentedString(idPratica)).append("\n");
        sb.append("    codiceIpaEnte: ").append(toIndentedString(codiceIpaEnte)).append("\n");
        sb.append("    codiceTipologia: ").append(toIndentedString(codiceTipologia)).append("\n");
        sb.append("    oggetto: ").append(toIndentedString(oggetto)).append("\n");
        sb.append("    riassunto: ").append(toIndentedString(riassunto)).append("\n");
        sb.append("    utenteCreazionePratica: ").append(toIndentedString(utenteCreazionePratica)).append("\n");
        sb.append("    metadati: ").append(toIndentedString(metadati)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}