/*-
 * ========================LICENSE_START=================================
 * 
 * Copyright (C) 2025 Regione Piemonte
 * 
 * SPDX-FileCopyrightText: (C) Copyright 2025 Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/*
 * cosmo-servizi-fruitori-xp
 * API esposte da Cosmo per l'integrazione con i fruitori esterni
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.csi.scriva.scrivabesrv.business.be.helper.cosmo.dto;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Model che contiene i campi relativi alla notifica da creare
 */
@ApiModel(description = "Model che contiene i campi relativi alla notifica da creare")
public class CreaNotificaFruitoreRequest {
    private String codiceIpaEnte = null;

    private String idPratica = null;

    private String descrizione = null;

    private List<String> destinatari = new ArrayList<String>();

    public CreaNotificaFruitoreRequest codiceIpaEnte(String codiceIpaEnte) {
        this.codiceIpaEnte = codiceIpaEnte;
        return this;
    }

    /**
     * Get codiceIpaEnte
     *
     * @return codiceIpaEnte
     **/
    @ApiModelProperty(required = true, value = "")
    public String getCodiceIpaEnte() {
        return codiceIpaEnte;
    }

    public void setCodiceIpaEnte(String codiceIpaEnte) {
        this.codiceIpaEnte = codiceIpaEnte;
    }

    public CreaNotificaFruitoreRequest idPratica(String idPratica) {
        this.idPratica = idPratica;
        return this;
    }

    /**
     * Get idPratica
     *
     * @return idPratica
     **/
    @ApiModelProperty(value = "")
    public String getIdPratica() {
        return idPratica;
    }

    public void setIdPratica(String idPratica) {
        this.idPratica = idPratica;
    }

    public CreaNotificaFruitoreRequest descrizione(String descrizione) {
        this.descrizione = descrizione;
        return this;
    }

    /**
     * Get descrizione
     *
     * @return descrizione
     **/
    @ApiModelProperty(required = true, value = "")
    public String getDescrizione() {
        return descrizione;
    }

    public void setDescrizione(String descrizione) {
        this.descrizione = descrizione;
    }

    public CreaNotificaFruitoreRequest destinatari(List<String> destinatari) {
        this.destinatari = destinatari;
        return this;
    }

    public CreaNotificaFruitoreRequest addDestinatariItem(String destinatariItem) {
        this.destinatari.add(destinatariItem);
        return this;
    }

    /**
     * Get destinatari
     *
     * @return destinatari
     **/
    @ApiModelProperty(required = true, value = "")
    public List<String> getDestinatari() {
        return destinatari;
    }

    public void setDestinatari(List<String> destinatari) {
        this.destinatari = destinatari;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CreaNotificaFruitoreRequest creaNotificaFruitoreRequest = (CreaNotificaFruitoreRequest) o;
        return Objects.equals(this.codiceIpaEnte, creaNotificaFruitoreRequest.codiceIpaEnte) &&
                Objects.equals(this.idPratica, creaNotificaFruitoreRequest.idPratica) &&
                Objects.equals(this.descrizione, creaNotificaFruitoreRequest.descrizione) &&
                Objects.equals(this.destinatari, creaNotificaFruitoreRequest.destinatari);
    }

    @Override
    public int hashCode() {
        return Objects.hash(codiceIpaEnte, idPratica, descrizione, destinatari);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class CreaNotificaFruitoreRequest {\n");

        sb.append("    codiceIpaEnte: ").append(toIndentedString(codiceIpaEnte)).append("\n");
        sb.append("    idPratica: ").append(toIndentedString(idPratica)).append("\n");
        sb.append("    descrizione: ").append(toIndentedString(descrizione)).append("\n");
        sb.append("    destinatari: ").append(toIndentedString(destinatari)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}