/*-
 * ========================LICENSE_START=================================
 * 
 * Copyright (C) 2025 Regione Piemonte
 * 
 * SPDX-FileCopyrightText: (C) Copyright 2025 Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/*
 * cosmo-servizi-fruitori-xp
 * API esposte da Cosmo per l'integrazione con i fruitori esterni
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.csi.scriva.scrivabesrv.business.be.helper.cosmo.dto;

import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Model che contiene i campi relativi ai documenti da creare
 */
public class CreaDocumentiFruitoreRequest {
    private List<CreaDocumentoFruitoreRequest> documenti = new ArrayList<CreaDocumentoFruitoreRequest>();

    private String idPratica = null;

    private String codiceIpaEnte = null;

    public CreaDocumentiFruitoreRequest documenti(List<CreaDocumentoFruitoreRequest> documenti) {
        this.documenti = documenti;
        return this;
    }

    public CreaDocumentiFruitoreRequest addDocumentiItem(CreaDocumentoFruitoreRequest documentiItem) {
        this.documenti.add(documentiItem);
        return this;
    }

    /**
     * Get documenti
     *
     * @return documenti
     **/
    @ApiModelProperty(required = true, value = "")
    public List<CreaDocumentoFruitoreRequest> getDocumenti() {
        return documenti;
    }

    public void setDocumenti(List<CreaDocumentoFruitoreRequest> documenti) {
        this.documenti = documenti;
    }

    public CreaDocumentiFruitoreRequest idPratica(String idPratica) {
        this.idPratica = idPratica;
        return this;
    }

    /**
     * Get idPratica
     *
     * @return idPratica
     **/
    @ApiModelProperty(required = true, value = "")
    public String getIdPratica() {
        return idPratica;
    }

    public void setIdPratica(String idPratica) {
        this.idPratica = idPratica;
    }

    public CreaDocumentiFruitoreRequest codiceIpaEnte(String codiceIpaEnte) {
        this.codiceIpaEnte = codiceIpaEnte;
        return this;
    }

    /**
     * Get codiceIpaEnte
     *
     * @return codiceIpaEnte
     **/
    @ApiModelProperty(required = true, value = "")
    public String getCodiceIpaEnte() {
        return codiceIpaEnte;
    }

    public void setCodiceIpaEnte(String codiceIpaEnte) {
        this.codiceIpaEnte = codiceIpaEnte;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CreaDocumentiFruitoreRequest creaDocumentiFruitoreRequest = (CreaDocumentiFruitoreRequest) o;
        return Objects.equals(this.documenti, creaDocumentiFruitoreRequest.documenti) &&
                Objects.equals(this.idPratica, creaDocumentiFruitoreRequest.idPratica) &&
                Objects.equals(this.codiceIpaEnte, creaDocumentiFruitoreRequest.codiceIpaEnte);
    }

    @Override
    public int hashCode() {
        return Objects.hash(documenti, idPratica, codiceIpaEnte);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class CreaDocumentiFruitoreRequest {\n");

        sb.append("    documenti: ").append(toIndentedString(documenti)).append("\n");
        sb.append("    idPratica: ").append(toIndentedString(idPratica)).append("\n");
        sb.append("    codiceIpaEnte: ").append(toIndentedString(codiceIpaEnte)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}