/*-
 * ========================LICENSE_START=================================
 * 
 * Copyright (C) 2025 Regione Piemonte
 * 
 * SPDX-FileCopyrightText: (C) Copyright 2025 Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/*
 * cosmo-servizi-fruitori-xp
 * API esposte da Cosmo per l'integrazione con i fruitori esterni
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.csi.scriva.scrivabesrv.business.be.helper.cosmo.dto;

import io.swagger.annotations.ApiModelProperty;

import java.time.OffsetDateTime;
import java.util.Objects;

/**
 * CreaEventoFruitoreRequest
 */
public class CreaEventoFruitoreRequest {
    private String codiceIpaEnte = null;

    private String destinatario = null;

    private String titolo = null;

    private String descrizione = null;

    private OffsetDateTime scadenza = null;

    public CreaEventoFruitoreRequest codiceIpaEnte(String codiceIpaEnte) {
        this.codiceIpaEnte = codiceIpaEnte;
        return this;
    }

    /**
     * Get codiceIpaEnte
     *
     * @return codiceIpaEnte
     **/
    @ApiModelProperty(required = true, value = "")
    public String getCodiceIpaEnte() {
        return codiceIpaEnte;
    }

    public void setCodiceIpaEnte(String codiceIpaEnte) {
        this.codiceIpaEnte = codiceIpaEnte;
    }

    public CreaEventoFruitoreRequest destinatario(String destinatario) {
        this.destinatario = destinatario;
        return this;
    }

    /**
     * Get destinatario
     *
     * @return destinatario
     **/
    @ApiModelProperty(required = true, value = "")
    public String getDestinatario() {
        return destinatario;
    }

    public void setDestinatario(String destinatario) {
        this.destinatario = destinatario;
    }

    public CreaEventoFruitoreRequest titolo(String titolo) {
        this.titolo = titolo;
        return this;
    }

    /**
     * Get titolo
     *
     * @return titolo
     **/
    @ApiModelProperty(required = true, value = "")
    public String getTitolo() {
        return titolo;
    }

    public void setTitolo(String titolo) {
        this.titolo = titolo;
    }

    public CreaEventoFruitoreRequest descrizione(String descrizione) {
        this.descrizione = descrizione;
        return this;
    }

    /**
     * Get descrizione
     *
     * @return descrizione
     **/
    @ApiModelProperty(required = true, value = "")
    public String getDescrizione() {
        return descrizione;
    }

    public void setDescrizione(String descrizione) {
        this.descrizione = descrizione;
    }

    public CreaEventoFruitoreRequest scadenza(OffsetDateTime scadenza) {
        this.scadenza = scadenza;
        return this;
    }

    /**
     * Get scadenza
     *
     * @return scadenza
     **/
    @ApiModelProperty(required = true, value = "")
    public OffsetDateTime getScadenza() {
        return scadenza;
    }

    public void setScadenza(OffsetDateTime scadenza) {
        this.scadenza = scadenza;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CreaEventoFruitoreRequest creaEventoFruitoreRequest = (CreaEventoFruitoreRequest) o;
        return Objects.equals(this.codiceIpaEnte, creaEventoFruitoreRequest.codiceIpaEnte) &&
                Objects.equals(this.destinatario, creaEventoFruitoreRequest.destinatario) &&
                Objects.equals(this.titolo, creaEventoFruitoreRequest.titolo) &&
                Objects.equals(this.descrizione, creaEventoFruitoreRequest.descrizione) &&
                Objects.equals(this.scadenza, creaEventoFruitoreRequest.scadenza);
    }

    @Override
    public int hashCode() {
        return Objects.hash(codiceIpaEnte, destinatario, titolo, descrizione, scadenza);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class CreaEventoFruitoreRequest {\n");

        sb.append("    codiceIpaEnte: ").append(toIndentedString(codiceIpaEnte)).append("\n");
        sb.append("    destinatario: ").append(toIndentedString(destinatario)).append("\n");
        sb.append("    titolo: ").append(toIndentedString(titolo)).append("\n");
        sb.append("    descrizione: ").append(toIndentedString(descrizione)).append("\n");
        sb.append("    scadenza: ").append(toIndentedString(scadenza)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}