/*-
 * ========================LICENSE_START=================================
 * 
 * Copyright (C) 2025 Regione Piemonte
 * 
 * SPDX-FileCopyrightText: (C) Copyright 2025 Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/*
 * cosmo-servizi-fruitori-xp
 * API esposte da Cosmo per l'integrazione con i fruitori esterni
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.csi.scriva.scrivabesrv.business.be.helper.cosmo.dto;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * Model che contiene i campi relativi al documento da creare
 */
@ApiModel(description = "Model che contiene i campi relativi al documento da creare")
public class CreaDocumentoFruitoreRequest {
    private String id = null;

    private String idPadre = null;

    private String codiceTipo = null;

    private String titolo = null;

    private String descrizione = null;

    private String autore = null;

    private String uploadUUID = null;

    private CreaDocumentoFruitoreContenutoRequest contenuto = null;

    public CreaDocumentoFruitoreRequest id(String id) {
        this.id = id;
        return this;
    }

    /**
     * Get id
     *
     * @return id
     **/
    @ApiModelProperty(value = "")
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public CreaDocumentoFruitoreRequest idPadre(String idPadre) {
        this.idPadre = idPadre;
        return this;
    }

    /**
     * Get idPadre
     *
     * @return idPadre
     **/
    @ApiModelProperty(value = "")
    public String getIdPadre() {
        return idPadre;
    }

    public void setIdPadre(String idPadre) {
        this.idPadre = idPadre;
    }

    public CreaDocumentoFruitoreRequest codiceTipo(String codiceTipo) {
        this.codiceTipo = codiceTipo;
        return this;
    }

    /**
     * Get codiceTipo
     *
     * @return codiceTipo
     **/
    @ApiModelProperty(value = "")
    public String getCodiceTipo() {
        return codiceTipo;
    }

    public void setCodiceTipo(String codiceTipo) {
        this.codiceTipo = codiceTipo;
    }

    public CreaDocumentoFruitoreRequest titolo(String titolo) {
        this.titolo = titolo;
        return this;
    }

    /**
     * Get titolo
     *
     * @return titolo
     **/
    @ApiModelProperty(value = "")
    public String getTitolo() {
        return titolo;
    }

    public void setTitolo(String titolo) {
        this.titolo = titolo;
    }

    public CreaDocumentoFruitoreRequest descrizione(String descrizione) {
        this.descrizione = descrizione;
        return this;
    }

    /**
     * Get descrizione
     *
     * @return descrizione
     **/
    @ApiModelProperty(value = "")
    public String getDescrizione() {
        return descrizione;
    }

    public void setDescrizione(String descrizione) {
        this.descrizione = descrizione;
    }

    public CreaDocumentoFruitoreRequest autore(String autore) {
        this.autore = autore;
        return this;
    }

    /**
     * Get autore
     *
     * @return autore
     **/
    @ApiModelProperty(value = "")
    public String getAutore() {
        return autore;
    }

    public void setAutore(String autore) {
        this.autore = autore;
    }

    public CreaDocumentoFruitoreRequest uploadUUID(String uploadUUID) {
        this.uploadUUID = uploadUUID;
        return this;
    }

    /**
     * Get uploadUUID
     *
     * @return uploadUUID
     **/
    @ApiModelProperty(value = "")
    public String getUploadUUID() {
        return uploadUUID;
    }

    public void setUploadUUID(String uploadUUID) {
        this.uploadUUID = uploadUUID;
    }

    public CreaDocumentoFruitoreRequest contenuto(CreaDocumentoFruitoreContenutoRequest contenuto) {
        this.contenuto = contenuto;
        return this;
    }

    /**
     * Get contenuto
     *
     * @return contenuto
     **/
    @ApiModelProperty(value = "")
    public CreaDocumentoFruitoreContenutoRequest getContenuto() {
        return contenuto;
    }

    public void setContenuto(CreaDocumentoFruitoreContenutoRequest contenuto) {
        this.contenuto = contenuto;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CreaDocumentoFruitoreRequest creaDocumentoFruitoreRequest = (CreaDocumentoFruitoreRequest) o;
        return Objects.equals(this.id, creaDocumentoFruitoreRequest.id) &&
                Objects.equals(this.idPadre, creaDocumentoFruitoreRequest.idPadre) &&
                Objects.equals(this.codiceTipo, creaDocumentoFruitoreRequest.codiceTipo) &&
                Objects.equals(this.titolo, creaDocumentoFruitoreRequest.titolo) &&
                Objects.equals(this.descrizione, creaDocumentoFruitoreRequest.descrizione) &&
                Objects.equals(this.autore, creaDocumentoFruitoreRequest.autore) &&
                Objects.equals(this.uploadUUID, creaDocumentoFruitoreRequest.uploadUUID) &&
                Objects.equals(this.contenuto, creaDocumentoFruitoreRequest.contenuto);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, idPadre, codiceTipo, titolo, descrizione, autore, uploadUUID, contenuto);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class CreaDocumentoFruitoreRequest {\n");

        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    idPadre: ").append(toIndentedString(idPadre)).append("\n");
        sb.append("    codiceTipo: ").append(toIndentedString(codiceTipo)).append("\n");
        sb.append("    titolo: ").append(toIndentedString(titolo)).append("\n");
        sb.append("    descrizione: ").append(toIndentedString(descrizione)).append("\n");
        sb.append("    autore: ").append(toIndentedString(autore)).append("\n");
        sb.append("    uploadUUID: ").append(toIndentedString(uploadUUID)).append("\n");
        sb.append("    contenuto: ").append(toIndentedString(contenuto)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}