/*-
 * ========================LICENSE_START=================================
 * 
 * Copyright (C) 2025 Regione Piemonte
 * 
 * SPDX-FileCopyrightText: (C) Copyright 2025 Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/*
 * cosmo-servizi-fruitori-xp
 * API esposte da Cosmo per l'integrazione con i fruitori esterni
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.csi.scriva.scrivabesrv.business.be.helper.cosmo.dto;

import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * CreaEventoFruitoreResponse
 */
public class CreaEventoFruitoreResponse {
    private String idEvento = null;

    public CreaEventoFruitoreResponse idEvento(String idEvento) {
        this.idEvento = idEvento;
        return this;
    }

    /**
     * Get idEvento
     *
     * @return idEvento
     **/
    @ApiModelProperty(required = true, value = "")
    public String getIdEvento() {
        return idEvento;
    }

    public void setIdEvento(String idEvento) {
        this.idEvento = idEvento;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CreaEventoFruitoreResponse creaEventoFruitoreResponse = (CreaEventoFruitoreResponse) o;
        return Objects.equals(this.idEvento, creaEventoFruitoreResponse.idEvento);
    }

    @Override
    public int hashCode() {
        return Objects.hash(idEvento);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class CreaEventoFruitoreResponse {\n");

        sb.append("    idEvento: ").append(toIndentedString(idEvento)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}