/*-
 * ========================LICENSE_START=================================
 * 
 * Copyright (C) 2025 Regione Piemonte
 * 
 * SPDX-FileCopyrightText: (C) Copyright 2025 Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/*
 * cosmo-servizi-fruitori
 * API esposte da Cosmo per l'integrazione con i fruitori esterni
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.csi.scriva.scrivabesrv.business.be.helper.cosmo.dto;

import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * CreaPraticaFruitoreResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-10-03T14:55:11.012Z")
public class CreaPraticaFruitoreResponse {
    private String idPratica = null;

    private String codiceIpaEnte = null;

    private String codiceTipologia = null;

    private String oggetto = null;

    private String riassunto = null;

    private String utenteCreazionePratica = null;

    private List<TagRidottoResponse> tags = null;

    public CreaPraticaFruitoreResponse idPratica(String idPratica) {
        this.idPratica = idPratica;
        return this;
    }

    /**
     * Get idPratica
     *
     * @return idPratica
     **/
    @ApiModelProperty(required = true, value = "")
    public String getIdPratica() {
        return idPratica;
    }

    public void setIdPratica(String idPratica) {
        this.idPratica = idPratica;
    }

    public CreaPraticaFruitoreResponse codiceIpaEnte(String codiceIpaEnte) {
        this.codiceIpaEnte = codiceIpaEnte;
        return this;
    }

    /**
     * Get codiceIpaEnte
     *
     * @return codiceIpaEnte
     **/
    @ApiModelProperty(required = true, value = "")
    public String getCodiceIpaEnte() {
        return codiceIpaEnte;
    }

    public void setCodiceIpaEnte(String codiceIpaEnte) {
        this.codiceIpaEnte = codiceIpaEnte;
    }

    public CreaPraticaFruitoreResponse codiceTipologia(String codiceTipologia) {
        this.codiceTipologia = codiceTipologia;
        return this;
    }

    /**
     * Get codiceTipologia
     *
     * @return codiceTipologia
     **/
    @ApiModelProperty(required = true, value = "")
    public String getCodiceTipologia() {
        return codiceTipologia;
    }

    public void setCodiceTipologia(String codiceTipologia) {
        this.codiceTipologia = codiceTipologia;
    }

    public CreaPraticaFruitoreResponse oggetto(String oggetto) {
        this.oggetto = oggetto;
        return this;
    }

    /**
     * Get oggetto
     *
     * @return oggetto
     **/
    @ApiModelProperty(required = true, value = "")
    public String getOggetto() {
        return oggetto;
    }

    public void setOggetto(String oggetto) {
        this.oggetto = oggetto;
    }

    public CreaPraticaFruitoreResponse riassunto(String riassunto) {
        this.riassunto = riassunto;
        return this;
    }

    /**
     * Get riassunto
     *
     * @return riassunto
     **/
    @ApiModelProperty(value = "")
    public String getRiassunto() {
        return riassunto;
    }

    public void setRiassunto(String riassunto) {
        this.riassunto = riassunto;
    }

    public CreaPraticaFruitoreResponse utenteCreazionePratica(String utenteCreazionePratica) {
        this.utenteCreazionePratica = utenteCreazionePratica;
        return this;
    }

    /**
     * Get utenteCreazionePratica
     *
     * @return utenteCreazionePratica
     **/
    @ApiModelProperty(value = "")
    public String getUtenteCreazionePratica() {
        return utenteCreazionePratica;
    }

    public void setUtenteCreazionePratica(String utenteCreazionePratica) {
        this.utenteCreazionePratica = utenteCreazionePratica;
    }

    public CreaPraticaFruitoreResponse tags(List<TagRidottoResponse> tags) {
        this.tags = tags;
        return this;
    }

    public CreaPraticaFruitoreResponse addTagsItem(TagRidottoResponse tagsItem) {
        if (this.tags == null) {
            this.tags = new ArrayList<TagRidottoResponse>();
        }
        this.tags.add(tagsItem);
        return this;
    }

    /**
     * Get tags
     *
     * @return tags
     **/
    @ApiModelProperty(value = "")
    public List<TagRidottoResponse> getTags() {
        return tags;
    }

    public void setTags(List<TagRidottoResponse> tags) {
        this.tags = tags;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CreaPraticaFruitoreResponse creaPraticaFruitoreResponse = (CreaPraticaFruitoreResponse) o;
        return Objects.equals(this.idPratica, creaPraticaFruitoreResponse.idPratica) &&
                Objects.equals(this.codiceIpaEnte, creaPraticaFruitoreResponse.codiceIpaEnte) &&
                Objects.equals(this.codiceTipologia, creaPraticaFruitoreResponse.codiceTipologia) &&
                Objects.equals(this.oggetto, creaPraticaFruitoreResponse.oggetto) &&
                Objects.equals(this.riassunto, creaPraticaFruitoreResponse.riassunto) &&
                Objects.equals(this.utenteCreazionePratica, creaPraticaFruitoreResponse.utenteCreazionePratica) &&
                Objects.equals(this.tags, creaPraticaFruitoreResponse.tags);
    }

    @Override
    public int hashCode() {
        return Objects.hash(idPratica, codiceIpaEnte, codiceTipologia, oggetto, riassunto, utenteCreazionePratica, tags);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class CreaPraticaFruitoreResponse {\n");

        sb.append("    idPratica: ").append(toIndentedString(idPratica)).append("\n");
        sb.append("    codiceIpaEnte: ").append(toIndentedString(codiceIpaEnte)).append("\n");
        sb.append("    codiceTipologia: ").append(toIndentedString(codiceTipologia)).append("\n");
        sb.append("    oggetto: ").append(toIndentedString(oggetto)).append("\n");
        sb.append("    riassunto: ").append(toIndentedString(riassunto)).append("\n");
        sb.append("    utenteCreazionePratica: ").append(toIndentedString(utenteCreazionePratica)).append("\n");
        sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}