/*-
 * ========================LICENSE_START=================================
 * 
 * Copyright (C) 2025 Regione Piemonte
 * 
 * SPDX-FileCopyrightText: (C) Copyright 2025 Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/*
 * cosmo-servizi-fruitori-xp
 * API esposte da Cosmo per l'integrazione con i fruitori esterni
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.csi.scriva.scrivabesrv.business.be.helper.cosmo.dto;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * Model che contiene i dati sul contenuto fisico
 */
@ApiModel(description = "Model che contiene i dati sul contenuto fisico")
public class CreaDocumentoFruitoreContenutoRequest {
    private String nomeFile = null;

    private String mimeType = null;

    private String contenutoFisico = null;

    public CreaDocumentoFruitoreContenutoRequest nomeFile(String nomeFile) {
        this.nomeFile = nomeFile;
        return this;
    }

    /**
     * Get nomeFile
     *
     * @return nomeFile
     **/
    @ApiModelProperty(required = true, value = "")
    public String getNomeFile() {
        return nomeFile;
    }

    public void setNomeFile(String nomeFile) {
        this.nomeFile = nomeFile;
    }

    public CreaDocumentoFruitoreContenutoRequest mimeType(String mimeType) {
        this.mimeType = mimeType;
        return this;
    }

    /**
     * Get mimeType
     *
     * @return mimeType
     **/
    @ApiModelProperty(value = "")
    public String getMimeType() {
        return mimeType;
    }

    public void setMimeType(String mimeType) {
        this.mimeType = mimeType;
    }

    public CreaDocumentoFruitoreContenutoRequest contenutoFisico(String contenutoFisico) {
        this.contenutoFisico = contenutoFisico;
        return this;
    }

    /**
     * Get contenutoFisico
     *
     * @return contenutoFisico
     **/
    @ApiModelProperty(required = true, value = "")
    public String getContenutoFisico() {
        return contenutoFisico;
    }

    public void setContenutoFisico(String contenutoFisico) {
        this.contenutoFisico = contenutoFisico;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CreaDocumentoFruitoreContenutoRequest creaDocumentoFruitoreContenutoRequest = (CreaDocumentoFruitoreContenutoRequest) o;
        return Objects.equals(this.nomeFile, creaDocumentoFruitoreContenutoRequest.nomeFile) &&
                Objects.equals(this.mimeType, creaDocumentoFruitoreContenutoRequest.mimeType) &&
                Objects.equals(this.contenutoFisico, creaDocumentoFruitoreContenutoRequest.contenutoFisico);
    }

    @Override
    public int hashCode() {
        return Objects.hash(nomeFile, mimeType, contenutoFisico);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class CreaDocumentoFruitoreContenutoRequest {\n");

        sb.append("    nomeFile: ").append(toIndentedString(nomeFile)).append("\n");
        sb.append("    mimeType: ").append(toIndentedString(mimeType)).append("\n");
        sb.append("    contenutoFisico: ").append(toIndentedString(contenutoFisico)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}