/*-
 * ========================LICENSE_START=================================
 * 
 * Copyright (C) 2025 Regione Piemonte
 * 
 * SPDX-FileCopyrightText: (C) Copyright 2025 Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/*
 * cosmo-servizi-fruitori-xp
 * API esposte da Cosmo per l'integrazione con i fruitori esterni
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.csi.scriva.scrivabesrv.business.be.helper.cosmo.dto;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Model che contiene i campi relativi al documento da creare
 */
@ApiModel(description = "Model che contiene i campi relativi al documento da creare")
public class DocumentoFruitore {
    private String id = null;

    private String idPadre = null;

    private String idPratica = null;

    private String codiceStato = null;

    private String codiceTipo = null;

    private String titolo = null;

    private String descrizione = null;

    private String autore = null;

    private List<DocumentoFruitore> allegati = null;

    public DocumentoFruitore id(String id) {
        this.id = id;
        return this;
    }

    /**
     * Get id
     *
     * @return id
     **/
    @ApiModelProperty(required = true, value = "")
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public DocumentoFruitore idPadre(String idPadre) {
        this.idPadre = idPadre;
        return this;
    }

    /**
     * Get idPadre
     *
     * @return idPadre
     **/
    @ApiModelProperty(value = "")
    public String getIdPadre() {
        return idPadre;
    }

    public void setIdPadre(String idPadre) {
        this.idPadre = idPadre;
    }

    public DocumentoFruitore idPratica(String idPratica) {
        this.idPratica = idPratica;
        return this;
    }

    /**
     * Get idPratica
     *
     * @return idPratica
     **/
    @ApiModelProperty(required = true, value = "")
    public String getIdPratica() {
        return idPratica;
    }

    public void setIdPratica(String idPratica) {
        this.idPratica = idPratica;
    }

    public DocumentoFruitore codiceStato(String codiceStato) {
        this.codiceStato = codiceStato;
        return this;
    }

    /**
     * Get codiceStato
     *
     * @return codiceStato
     **/
    @ApiModelProperty(required = true, value = "")
    public String getCodiceStato() {
        return codiceStato;
    }

    public void setCodiceStato(String codiceStato) {
        this.codiceStato = codiceStato;
    }

    public DocumentoFruitore codiceTipo(String codiceTipo) {
        this.codiceTipo = codiceTipo;
        return this;
    }

    /**
     * Get codiceTipo
     *
     * @return codiceTipo
     **/
    @ApiModelProperty(value = "")
    public String getCodiceTipo() {
        return codiceTipo;
    }

    public void setCodiceTipo(String codiceTipo) {
        this.codiceTipo = codiceTipo;
    }

    public DocumentoFruitore titolo(String titolo) {
        this.titolo = titolo;
        return this;
    }

    /**
     * Get titolo
     *
     * @return titolo
     **/
    @ApiModelProperty(value = "")
    public String getTitolo() {
        return titolo;
    }

    public void setTitolo(String titolo) {
        this.titolo = titolo;
    }

    public DocumentoFruitore descrizione(String descrizione) {
        this.descrizione = descrizione;
        return this;
    }

    /**
     * Get descrizione
     *
     * @return descrizione
     **/
    @ApiModelProperty(value = "")
    public String getDescrizione() {
        return descrizione;
    }

    public void setDescrizione(String descrizione) {
        this.descrizione = descrizione;
    }

    public DocumentoFruitore autore(String autore) {
        this.autore = autore;
        return this;
    }

    /**
     * Get autore
     *
     * @return autore
     **/
    @ApiModelProperty(value = "")
    public String getAutore() {
        return autore;
    }

    public void setAutore(String autore) {
        this.autore = autore;
    }

    public DocumentoFruitore allegati(List<DocumentoFruitore> allegati) {
        this.allegati = allegati;
        return this;
    }

    public DocumentoFruitore addAllegatiItem(DocumentoFruitore allegatiItem) {
        if (this.allegati == null) {
            this.allegati = new ArrayList<DocumentoFruitore>();
        }
        this.allegati.add(allegatiItem);
        return this;
    }

    /**
     * Get allegati
     *
     * @return allegati
     **/
    @ApiModelProperty(value = "")
    public List<DocumentoFruitore> getAllegati() {
        return allegati;
    }

    public void setAllegati(List<DocumentoFruitore> allegati) {
        this.allegati = allegati;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        DocumentoFruitore documentoFruitore = (DocumentoFruitore) o;
        return Objects.equals(this.id, documentoFruitore.id) &&
                Objects.equals(this.idPadre, documentoFruitore.idPadre) &&
                Objects.equals(this.idPratica, documentoFruitore.idPratica) &&
                Objects.equals(this.codiceStato, documentoFruitore.codiceStato) &&
                Objects.equals(this.codiceTipo, documentoFruitore.codiceTipo) &&
                Objects.equals(this.titolo, documentoFruitore.titolo) &&
                Objects.equals(this.descrizione, documentoFruitore.descrizione) &&
                Objects.equals(this.autore, documentoFruitore.autore) &&
                Objects.equals(this.allegati, documentoFruitore.allegati);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, idPadre, idPratica, codiceStato, codiceTipo, titolo, descrizione, autore, allegati);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class DocumentoFruitore {\n");

        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    idPadre: ").append(toIndentedString(idPadre)).append("\n");
        sb.append("    idPratica: ").append(toIndentedString(idPratica)).append("\n");
        sb.append("    codiceStato: ").append(toIndentedString(codiceStato)).append("\n");
        sb.append("    codiceTipo: ").append(toIndentedString(codiceTipo)).append("\n");
        sb.append("    titolo: ").append(toIndentedString(titolo)).append("\n");
        sb.append("    descrizione: ").append(toIndentedString(descrizione)).append("\n");
        sb.append("    autore: ").append(toIndentedString(autore)).append("\n");
        sb.append("    allegati: ").append(toIndentedString(allegati)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}