/*-
 * ========================LICENSE_START=================================
 * 
 * Copyright (C) 2025 Regione Piemonte
 * 
 * SPDX-FileCopyrightText: (C) Copyright 2025 Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/*
 * cosmo-servizi-fruitori-xp
 * API esposte da Cosmo per l'integrazione con i fruitori esterni
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.csi.scriva.scrivabesrv.business.be.helper.cosmo.dto;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * Model che contiene i campi relativi all&#39;esito dell&#39;invio di una notifica
 */
@ApiModel(description = "Model che contiene i campi relativi all'esito dell'invio di una notifica")
public class EsitoCreazioneNotificaFruitoreResponse {
    private String destinatario = null;

    private Object esito = null;

    public EsitoCreazioneNotificaFruitoreResponse destinatario(String destinatario) {
        this.destinatario = destinatario;
        return this;
    }

    /**
     * Get destinatario
     *
     * @return destinatario
     **/
    @ApiModelProperty(required = true, value = "")
    public String getDestinatario() {
        return destinatario;
    }

    public void setDestinatario(String destinatario) {
        this.destinatario = destinatario;
    }

    public EsitoCreazioneNotificaFruitoreResponse esito(Object esito) {
        this.esito = esito;
        return this;
    }

    /**
     * Model che contiene i campi che vengono restituiti in caso di errore da tutte le API
     *
     * @return esito
     **/
    @ApiModelProperty(required = true, value = "Model che contiene i campi che vengono restituiti in caso di errore da tutte le API")
    public Object getEsito() {
        return esito;
    }

    public void setEsito(Object esito) {
        this.esito = esito;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        EsitoCreazioneNotificaFruitoreResponse esitoCreazioneNotificaFruitoreResponse = (EsitoCreazioneNotificaFruitoreResponse) o;
        return Objects.equals(this.destinatario, esitoCreazioneNotificaFruitoreResponse.destinatario) &&
                Objects.equals(this.esito, esitoCreazioneNotificaFruitoreResponse.esito);
    }

    @Override
    public int hashCode() {
        return Objects.hash(destinatario, esito);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class EsitoCreazioneNotificaFruitoreResponse {\n");

        sb.append("    destinatario: ").append(toIndentedString(destinatario)).append("\n");
        sb.append("    esito: ").append(toIndentedString(esito)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}