/*-
 * ========================LICENSE_START=================================
 * 
 * Copyright (C) 2025 Regione Piemonte
 * 
 * SPDX-FileCopyrightText: (C) Copyright 2025 Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/*
 * cosmo-servizi-fruitori-xp
 * API esposte da Cosmo per l'integrazione con i fruitori esterni
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.csi.scriva.scrivabesrv.business.be.helper.cosmo.dto;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * Model che contiene i campi relativi all&#39;esito della creazione di un documento
 */
@ApiModel(description = "Model che contiene i campi relativi all'esito della creazione di un documento")
public class EsitoCreazioneDocumentoFruitore {
    private CreaDocumentoFruitoreRequest input = null;

    private DocumentoFruitore output = null;

    private Object esito = null;

    public EsitoCreazioneDocumentoFruitore input(CreaDocumentoFruitoreRequest input) {
        this.input = input;
        return this;
    }

    /**
     * Get input
     *
     * @return input
     **/
    @ApiModelProperty(value = "")
    public CreaDocumentoFruitoreRequest getInput() {
        return input;
    }

    public void setInput(CreaDocumentoFruitoreRequest input) {
        this.input = input;
    }

    public EsitoCreazioneDocumentoFruitore output(DocumentoFruitore output) {
        this.output = output;
        return this;
    }

    /**
     * Get output
     *
     * @return output
     **/
    @ApiModelProperty(value = "")
    public DocumentoFruitore getOutput() {
        return output;
    }

    public void setOutput(DocumentoFruitore output) {
        this.output = output;
    }

    public EsitoCreazioneDocumentoFruitore esito(Object esito) {
        this.esito = esito;
        return this;
    }

    /**
     * Model che contiene i campi che vengono restituiti in caso di errore da tutte le API
     *
     * @return esito
     **/
    @ApiModelProperty(required = true, value = "Model che contiene i campi che vengono restituiti in caso di errore da tutte le API")
    public Object getEsito() {
        return esito;
    }

    public void setEsito(Object esito) {
        this.esito = esito;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        EsitoCreazioneDocumentoFruitore esitoCreazioneDocumentoFruitore = (EsitoCreazioneDocumentoFruitore) o;
        return Objects.equals(this.input, esitoCreazioneDocumentoFruitore.input) &&
                Objects.equals(this.output, esitoCreazioneDocumentoFruitore.output) &&
                Objects.equals(this.esito, esitoCreazioneDocumentoFruitore.esito);
    }

    @Override
    public int hashCode() {
        return Objects.hash(input, output, esito);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class EsitoCreazioneDocumentoFruitore {\n");

        sb.append("    input: ").append(toIndentedString(input)).append("\n");
        sb.append("    output: ").append(toIndentedString(output)).append("\n");
        sb.append("    esito: ").append(toIndentedString(esito)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}