/*-
 * ========================LICENSE_START=================================
 * 
 * Copyright (C) 2025 Regione Piemonte
 * 
 * SPDX-FileCopyrightText: (C) Copyright 2025 Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/*
 * cosmo-servizi-fruitori-xp
 * API esposte da Cosmo per l'integrazione con i fruitori esterni
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.csi.scriva.scrivabesrv.business.be.helper.cosmo.dto;

import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * EsitoCreazioneDocumentiFruitore
 */
public class EsitoCreazioneDocumentiFruitore {
    private List<EsitoCreazioneDocumentoFruitore> esiti = new ArrayList<EsitoCreazioneDocumentoFruitore>();

    public EsitoCreazioneDocumentiFruitore esiti(List<EsitoCreazioneDocumentoFruitore> esiti) {
        this.esiti = esiti;
        return this;
    }

    public EsitoCreazioneDocumentiFruitore addEsitiItem(EsitoCreazioneDocumentoFruitore esitiItem) {
        this.esiti.add(esitiItem);
        return this;
    }

    /**
     * Get esiti
     *
     * @return esiti
     **/
    @ApiModelProperty(required = true, value = "")
    public List<EsitoCreazioneDocumentoFruitore> getEsiti() {
        return esiti;
    }

    public void setEsiti(List<EsitoCreazioneDocumentoFruitore> esiti) {
        this.esiti = esiti;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        EsitoCreazioneDocumentiFruitore esitoCreazioneDocumentiFruitore = (EsitoCreazioneDocumentiFruitore) o;
        return Objects.equals(this.esiti, esitoCreazioneDocumentiFruitore.esiti);
    }

    @Override
    public int hashCode() {
        return Objects.hash(esiti);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class EsitoCreazioneDocumentiFruitore {\n");

        sb.append("    esiti: ").append(toIndentedString(esiti)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}