/*-
 * ========================LICENSE_START=================================
 * 
 * Copyright (C) 2025 Regione Piemonte
 * 
 * SPDX-FileCopyrightText: (C) Copyright 2025 Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/*
 * cosmo-servizi-fruitori-xp
 * API esposte da Cosmo per l'integrazione con i fruitori esterni
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.csi.scriva.scrivabesrv.business.be.helper.cosmo.dto;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Tutti i contenuti della pratica aggiornati alla data odierna
 */
@ApiModel(description = "Tutti i contenuti della pratica aggiornati alla data odierna")
public class GetPraticaFruitoreResponse {
    private String id = null;

    private String codiceIpaEnte = null;

    private Object tipo = null;

    private String oggetto = null;

    private Object stato = null;

    private String riassunto = null;

    private Object utenteCreazione = null;

    private OffsetDateTime dataCreazione = null;

    private OffsetDateTime dataFine = null;

    private OffsetDateTime dataCambioStato = null;

    private OffsetDateTime dataAggiornamento = null;

    private Object metadati = null;

    private List<Object> attivita = null;

    private List<Object> commenti = null;

    private List<Object> documenti = null;

    public GetPraticaFruitoreResponse id(String id) {
        this.id = id;
        return this;
    }

    /**
     * Get id
     *
     * @return id
     **/
    @ApiModelProperty(required = true, value = "")
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public GetPraticaFruitoreResponse codiceIpaEnte(String codiceIpaEnte) {
        this.codiceIpaEnte = codiceIpaEnte;
        return this;
    }

    /**
     * Get codiceIpaEnte
     *
     * @return codiceIpaEnte
     **/
    @ApiModelProperty(value = "")
    public String getCodiceIpaEnte() {
        return codiceIpaEnte;
    }

    public void setCodiceIpaEnte(String codiceIpaEnte) {
        this.codiceIpaEnte = codiceIpaEnte;
    }

    public GetPraticaFruitoreResponse tipo(Object tipo) {
        this.tipo = tipo;
        return this;
    }

    /**
     * Get tipo
     *
     * @return tipo
     **/
    @ApiModelProperty(value = "")
    public Object getTipo() {
        return tipo;
    }

    public void setTipo(Object tipo) {
        this.tipo = tipo;
    }

    public GetPraticaFruitoreResponse oggetto(String oggetto) {
        this.oggetto = oggetto;
        return this;
    }

    /**
     * Get oggetto
     *
     * @return oggetto
     **/
    @ApiModelProperty(value = "")
    public String getOggetto() {
        return oggetto;
    }

    public void setOggetto(String oggetto) {
        this.oggetto = oggetto;
    }

    public GetPraticaFruitoreResponse stato(Object stato) {
        this.stato = stato;
        return this;
    }

    /**
     * Get stato
     *
     * @return stato
     **/
    @ApiModelProperty(value = "")
    public Object getStato() {
        return stato;
    }

    public void setStato(Object stato) {
        this.stato = stato;
    }

    public GetPraticaFruitoreResponse riassunto(String riassunto) {
        this.riassunto = riassunto;
        return this;
    }

    /**
     * Get riassunto
     *
     * @return riassunto
     **/
    @ApiModelProperty(value = "")
    public String getRiassunto() {
        return riassunto;
    }

    public void setRiassunto(String riassunto) {
        this.riassunto = riassunto;
    }

    public GetPraticaFruitoreResponse utenteCreazione(Object utenteCreazione) {
        this.utenteCreazione = utenteCreazione;
        return this;
    }

    /**
     * Get utenteCreazione
     *
     * @return utenteCreazione
     **/
    @ApiModelProperty(value = "")
    public Object getUtenteCreazione() {
        return utenteCreazione;
    }

    public void setUtenteCreazione(Object utenteCreazione) {
        this.utenteCreazione = utenteCreazione;
    }

    public GetPraticaFruitoreResponse dataCreazione(OffsetDateTime dataCreazione) {
        this.dataCreazione = dataCreazione;
        return this;
    }

    /**
     * Get dataCreazione
     *
     * @return dataCreazione
     **/
    @ApiModelProperty(value = "")
    public OffsetDateTime getDataCreazione() {
        return dataCreazione;
    }

    public void setDataCreazione(OffsetDateTime dataCreazione) {
        this.dataCreazione = dataCreazione;
    }

    public GetPraticaFruitoreResponse dataFine(OffsetDateTime dataFine) {
        this.dataFine = dataFine;
        return this;
    }

    /**
     * Get dataFine
     *
     * @return dataFine
     **/
    @ApiModelProperty(value = "")
    public OffsetDateTime getDataFine() {
        return dataFine;
    }

    public void setDataFine(OffsetDateTime dataFine) {
        this.dataFine = dataFine;
    }

    public GetPraticaFruitoreResponse dataCambioStato(OffsetDateTime dataCambioStato) {
        this.dataCambioStato = dataCambioStato;
        return this;
    }

    /**
     * Get dataCambioStato
     *
     * @return dataCambioStato
     **/
    @ApiModelProperty(value = "")
    public OffsetDateTime getDataCambioStato() {
        return dataCambioStato;
    }

    public void setDataCambioStato(OffsetDateTime dataCambioStato) {
        this.dataCambioStato = dataCambioStato;
    }

    public GetPraticaFruitoreResponse dataAggiornamento(OffsetDateTime dataAggiornamento) {
        this.dataAggiornamento = dataAggiornamento;
        return this;
    }

    /**
     * Get dataAggiornamento
     *
     * @return dataAggiornamento
     **/
    @ApiModelProperty(value = "")
    public OffsetDateTime getDataAggiornamento() {
        return dataAggiornamento;
    }

    public void setDataAggiornamento(OffsetDateTime dataAggiornamento) {
        this.dataAggiornamento = dataAggiornamento;
    }

    public GetPraticaFruitoreResponse metadati(Object metadati) {
        this.metadati = metadati;
        return this;
    }

    /**
     * metadati della pratica in formato libero
     *
     * @return metadati
     **/
    @ApiModelProperty(value = "metadati della pratica in formato libero")
    public Object getMetadati() {
        return metadati;
    }

    public void setMetadati(Object metadati) {
        this.metadati = metadati;
    }

    public GetPraticaFruitoreResponse attivita(List<Object> attivita) {
        this.attivita = attivita;
        return this;
    }

    public GetPraticaFruitoreResponse addAttivitaItem(Object attivitaItem) {
        if (this.attivita == null) {
            this.attivita = new ArrayList<Object>();
        }
        this.attivita.add(attivitaItem);
        return this;
    }

    /**
     * array di tutte le attività della pratica in ordine cronologico, le attività concluse hanno dataFine not null
     *
     * @return attivita
     **/
    @ApiModelProperty(value = "array di tutte le attività della pratica in ordine cronologico, le attività concluse hanno dataFine not null")
    public List<Object> getAttivita() {
        return attivita;
    }

    public void setAttivita(List<Object> attivita) {
        this.attivita = attivita;
    }

    public GetPraticaFruitoreResponse commenti(List<Object> commenti) {
        this.commenti = commenti;
        return this;
    }

    public GetPraticaFruitoreResponse addCommentiItem(Object commentiItem) {
        if (this.commenti == null) {
            this.commenti = new ArrayList<Object>();
        }
        this.commenti.add(commentiItem);
        return this;
    }

    /**
     * array in ordine cronologico dei commenti della pratica
     *
     * @return commenti
     **/
    @ApiModelProperty(value = "array in ordine cronologico dei commenti della pratica")
    public List<Object> getCommenti() {
        return commenti;
    }

    public void setCommenti(List<Object> commenti) {
        this.commenti = commenti;
    }

    public GetPraticaFruitoreResponse documenti(List<Object> documenti) {
        this.documenti = documenti;
        return this;
    }

    public GetPraticaFruitoreResponse addDocumentiItem(Object documentiItem) {
        if (this.documenti == null) {
            this.documenti = new ArrayList<Object>();
        }
        this.documenti.add(documentiItem);
        return this;
    }

    /**
     * array dei documenti della pratica
     *
     * @return documenti
     **/
    @ApiModelProperty(value = "array dei documenti della pratica")
    public List<Object> getDocumenti() {
        return documenti;
    }

    public void setDocumenti(List<Object> documenti) {
        this.documenti = documenti;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetPraticaFruitoreResponse getPraticaFruitoreResponse = (GetPraticaFruitoreResponse) o;
        return Objects.equals(this.id, getPraticaFruitoreResponse.id) &&
                Objects.equals(this.codiceIpaEnte, getPraticaFruitoreResponse.codiceIpaEnte) &&
                Objects.equals(this.tipo, getPraticaFruitoreResponse.tipo) &&
                Objects.equals(this.oggetto, getPraticaFruitoreResponse.oggetto) &&
                Objects.equals(this.stato, getPraticaFruitoreResponse.stato) &&
                Objects.equals(this.riassunto, getPraticaFruitoreResponse.riassunto) &&
                Objects.equals(this.utenteCreazione, getPraticaFruitoreResponse.utenteCreazione) &&
                Objects.equals(this.dataCreazione, getPraticaFruitoreResponse.dataCreazione) &&
                Objects.equals(this.dataFine, getPraticaFruitoreResponse.dataFine) &&
                Objects.equals(this.dataCambioStato, getPraticaFruitoreResponse.dataCambioStato) &&
                Objects.equals(this.dataAggiornamento, getPraticaFruitoreResponse.dataAggiornamento) &&
                Objects.equals(this.metadati, getPraticaFruitoreResponse.metadati) &&
                Objects.equals(this.attivita, getPraticaFruitoreResponse.attivita) &&
                Objects.equals(this.commenti, getPraticaFruitoreResponse.commenti) &&
                Objects.equals(this.documenti, getPraticaFruitoreResponse.documenti);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, codiceIpaEnte, tipo, oggetto, stato, riassunto, utenteCreazione, dataCreazione, dataFine, dataCambioStato, dataAggiornamento, metadati, attivita, commenti, documenti);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class GetPraticaFruitoreResponse {\n");

        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    codiceIpaEnte: ").append(toIndentedString(codiceIpaEnte)).append("\n");
        sb.append("    tipo: ").append(toIndentedString(tipo)).append("\n");
        sb.append("    oggetto: ").append(toIndentedString(oggetto)).append("\n");
        sb.append("    stato: ").append(toIndentedString(stato)).append("\n");
        sb.append("    riassunto: ").append(toIndentedString(riassunto)).append("\n");
        sb.append("    utenteCreazione: ").append(toIndentedString(utenteCreazione)).append("\n");
        sb.append("    dataCreazione: ").append(toIndentedString(dataCreazione)).append("\n");
        sb.append("    dataFine: ").append(toIndentedString(dataFine)).append("\n");
        sb.append("    dataCambioStato: ").append(toIndentedString(dataCambioStato)).append("\n");
        sb.append("    dataAggiornamento: ").append(toIndentedString(dataAggiornamento)).append("\n");
        sb.append("    metadati: ").append(toIndentedString(metadati)).append("\n");
        sb.append("    attivita: ").append(toIndentedString(attivita)).append("\n");
        sb.append("    commenti: ").append(toIndentedString(commenti)).append("\n");
        sb.append("    documenti: ").append(toIndentedString(documenti)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}