/*-
 * ========================LICENSE_START=================================
 * 
 * Copyright (C) 2025 Regione Piemonte
 * 
 * SPDX-FileCopyrightText: (C) Copyright 2025 Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/*
 * cosmo-servizi-fruitori-xp
 * API esposte da Cosmo per l'integrazione con i fruitori esterni
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.csi.scriva.scrivabesrv.business.be.helper.cosmo.dto;

import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * InviaSegnaleFruitoreVariabileRequest
 */
public class InviaSegnaleFruitoreVariabileRequest {
    private String nome = null;

    private String valore = null;

    public InviaSegnaleFruitoreVariabileRequest nome(String nome) {
        this.nome = nome;
        return this;
    }

    /**
     * Get nome
     *
     * @return nome
     **/
    @ApiModelProperty(required = true, value = "")
    public String getNome() {
        return nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public InviaSegnaleFruitoreVariabileRequest valore(String valore) {
        this.valore = valore;
        return this;
    }

    /**
     * Get valore
     *
     * @return valore
     **/
    @ApiModelProperty(required = true, value = "")
    public String getValore() {
        return valore;
    }

    public void setValore(String valore) {
        this.valore = valore;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        InviaSegnaleFruitoreVariabileRequest inviaSegnaleFruitoreVariabileRequest = (InviaSegnaleFruitoreVariabileRequest) o;
        return Objects.equals(this.nome, inviaSegnaleFruitoreVariabileRequest.nome) &&
                Objects.equals(this.valore, inviaSegnaleFruitoreVariabileRequest.valore);
    }

    @Override
    public int hashCode() {
        return Objects.hash(nome, valore);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class InviaSegnaleFruitoreVariabileRequest {\n");

        sb.append("    nome: ").append(toIndentedString(nome)).append("\n");
        sb.append("    valore: ").append(toIndentedString(valore)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}