/*-
 * ========================LICENSE_START=================================
 * 
 * Copyright (C) 2025 Regione Piemonte
 * 
 * SPDX-FileCopyrightText: (C) Copyright 2025 Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/*
 * cosmo-servizi-fruitori
 * API esposte da Cosmo per l'integrazione con i fruitori esterni
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.csi.scriva.scrivabesrv.business.be.helper.cosmo.dto;

import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * TagRidotto
 */
public class TagRidotto {
    private String codice = null;

    private String descrizione = null;

    private TipoTag tipoTag = null;

    public TagRidotto codice(String codice) {
        this.codice = codice;
        return this;
    }

    /**
     * Get codice
     *
     * @return codice
     **/
    @ApiModelProperty(required = true, value = "")
    public String getCodice() {
        return codice;
    }

    public void setCodice(String codice) {
        this.codice = codice;
    }

    public TagRidotto descrizione(String descrizione) {
        this.descrizione = descrizione;
        return this;
    }

    /**
     * Get descrizione
     *
     * @return descrizione
     **/
    @ApiModelProperty(value = "")
    public String getDescrizione() {
        return descrizione;
    }

    public void setDescrizione(String descrizione) {
        this.descrizione = descrizione;
    }

    public TagRidotto tipoTag(TipoTag tipoTag) {
        this.tipoTag = tipoTag;
        return this;
    }

    /**
     * Get tipoTag
     *
     * @return tipoTag
     **/
    @ApiModelProperty(required = true, value = "")
    public TipoTag getTipoTag() {
        return tipoTag;
    }

    public void setTipoTag(TipoTag tipoTag) {
        this.tipoTag = tipoTag;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        TagRidotto tagRidotto = (TagRidotto) o;
        return Objects.equals(this.codice, tagRidotto.codice) &&
                Objects.equals(this.descrizione, tagRidotto.descrizione) &&
                Objects.equals(this.tipoTag, tagRidotto.tipoTag);
    }

    @Override
    public int hashCode() {
        return Objects.hash(codice, descrizione, tipoTag);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class TagRidotto {\n");

        sb.append("    codice: ").append(toIndentedString(codice)).append("\n");
        sb.append("    descrizione: ").append(toIndentedString(descrizione)).append("\n");
        sb.append("    tipoTag: ").append(toIndentedString(tipoTag)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}