/*-
 * ========================LICENSE_START=================================
 * 
 * Copyright (C) 2025 Regione Piemonte
 * 
 * SPDX-FileCopyrightText: (C) Copyright 2025 Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/*
 * ricerca-fulltext-geografica
 * Servizi di ricerca full text con localizzazione geografica
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.csi.scriva.scrivabesrv.business.be.helper.loccsi.dto;

import io.swagger.annotations.ApiModelProperty;

import java.util.HashMap;
import java.util.Map;
import java.util.Objects;

/**
 * AttributeDescriptor
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-02-24T08:29:11.008Z")
public class AttributeDescriptor {
  private String localName = null;

  private AttributeType type = null;

  private Object defaultValue = null;

  private Boolean nillable = null;

  private Integer minOccurs = null;

  private Integer maxOccurs = null;

  private Map<String, Object> userData = null;

  private Name name = null;

  public AttributeDescriptor localName(String localName) {
    this.localName = localName;
    return this;
  }

   /**
   * Get localName
   * @return localName
  **/
  @ApiModelProperty(value = "")
  public String getLocalName() {
    return localName;
  }

  public void setLocalName(String localName) {
    this.localName = localName;
  }

  public AttributeDescriptor type(AttributeType type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(value = "")
  public AttributeType getType() {
    return type;
  }

  public void setType(AttributeType type) {
    this.type = type;
  }

  public AttributeDescriptor defaultValue(Object defaultValue) {
    this.defaultValue = defaultValue;
    return this;
  }

   /**
   * Get defaultValue
   * @return defaultValue
  **/
  @ApiModelProperty(value = "")
  public Object getDefaultValue() {
    return defaultValue;
  }

  public void setDefaultValue(Object defaultValue) {
    this.defaultValue = defaultValue;
  }

  public AttributeDescriptor nillable(Boolean nillable) {
    this.nillable = nillable;
    return this;
  }

   /**
   * Get nillable
   * @return nillable
  **/
  @ApiModelProperty(value = "")
  public Boolean isNillable() {
    return nillable;
  }

  public void setNillable(Boolean nillable) {
    this.nillable = nillable;
  }

  public AttributeDescriptor minOccurs(Integer minOccurs) {
    this.minOccurs = minOccurs;
    return this;
  }

   /**
   * Get minOccurs
   * @return minOccurs
  **/
  @ApiModelProperty(value = "")
  public Integer getMinOccurs() {
    return minOccurs;
  }

  public void setMinOccurs(Integer minOccurs) {
    this.minOccurs = minOccurs;
  }

  public AttributeDescriptor maxOccurs(Integer maxOccurs) {
    this.maxOccurs = maxOccurs;
    return this;
  }

   /**
   * Get maxOccurs
   * @return maxOccurs
  **/
  @ApiModelProperty(value = "")
  public Integer getMaxOccurs() {
    return maxOccurs;
  }

  public void setMaxOccurs(Integer maxOccurs) {
    this.maxOccurs = maxOccurs;
  }

  public AttributeDescriptor userData(Map<String, Object> userData) {
    this.userData = userData;
    return this;
  }

  public AttributeDescriptor putUserDataItem(String key, Object userDataItem) {
    if (this.userData == null) {
      this.userData = new HashMap<String, Object>();
    }
    this.userData.put(key, userDataItem);
    return this;
  }

   /**
   * Get userData
   * @return userData
  **/
  @ApiModelProperty(value = "")
  public Map<String, Object> getUserData() {
    return userData;
  }

  public void setUserData(Map<String, Object> userData) {
    this.userData = userData;
  }

  public AttributeDescriptor name(Name name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public Name getName() {
    return name;
  }

  public void setName(Name name) {
    this.name = name;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AttributeDescriptor attributeDescriptor = (AttributeDescriptor) o;
    return Objects.equals(this.localName, attributeDescriptor.localName) &&
        Objects.equals(this.type, attributeDescriptor.type) &&
        Objects.equals(this.defaultValue, attributeDescriptor.defaultValue) &&
        Objects.equals(this.nillable, attributeDescriptor.nillable) &&
        Objects.equals(this.minOccurs, attributeDescriptor.minOccurs) &&
        Objects.equals(this.maxOccurs, attributeDescriptor.maxOccurs) &&
        Objects.equals(this.userData, attributeDescriptor.userData) &&
        Objects.equals(this.name, attributeDescriptor.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(localName, type, defaultValue, nillable, minOccurs, maxOccurs, userData, name);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AttributeDescriptor {\n");

    sb.append("    localName: ").append(toIndentedString(localName)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    defaultValue: ").append(toIndentedString(defaultValue)).append("\n");
    sb.append("    nillable: ").append(toIndentedString(nillable)).append("\n");
    sb.append("    minOccurs: ").append(toIndentedString(minOccurs)).append("\n");
    sb.append("    maxOccurs: ").append(toIndentedString(maxOccurs)).append("\n");
    sb.append("    userData: ").append(toIndentedString(userData)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}