/*-
 * ========================LICENSE_START=================================
 * 
 * Copyright (C) 2025 Regione Piemonte
 * 
 * SPDX-FileCopyrightText: (C) Copyright 2025 Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/*
 * ricerca-fulltext-geografica
 * Servizi di ricerca full text con localizzazione geografica
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.csi.scriva.scrivabesrv.business.be.helper.loccsi.dto;

import io.swagger.annotations.ApiModelProperty;

import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Citation
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-02-24T08:29:11.008Z")
public class Citation {
  private Series series = null;

  private InternationalString otherCitationDetails = null;

  private InternationalString collectiveTitle = null;

  private String isbn = null;

  private String issn = null;

  private List<CitationDate> dates = null;

  private InternationalString edition = null;

  private OffsetDateTime editionDate = null;

  private List<ResponsibleParty> citedResponsibleParties = null;

  private List<PresentationForm> presentationForm = null;

  private List<InternationalString> alternateTitles = null;

  private List<Identifier> identifiers = null;

  private InternationalString title = null;

  public Citation series(Series series) {
    this.series = series;
    return this;
  }

   /**
   * Get series
   * @return series
  **/
  @ApiModelProperty(value = "")
  public Series getSeries() {
    return series;
  }

  public void setSeries(Series series) {
    this.series = series;
  }

  public Citation otherCitationDetails(InternationalString otherCitationDetails) {
    this.otherCitationDetails = otherCitationDetails;
    return this;
  }

   /**
   * Get otherCitationDetails
   * @return otherCitationDetails
  **/
  @ApiModelProperty(value = "")
  public InternationalString getOtherCitationDetails() {
    return otherCitationDetails;
  }

  public void setOtherCitationDetails(InternationalString otherCitationDetails) {
    this.otherCitationDetails = otherCitationDetails;
  }

  public Citation collectiveTitle(InternationalString collectiveTitle) {
    this.collectiveTitle = collectiveTitle;
    return this;
  }

   /**
   * Get collectiveTitle
   * @return collectiveTitle
  **/
  @ApiModelProperty(value = "")
  public InternationalString getCollectiveTitle() {
    return collectiveTitle;
  }

  public void setCollectiveTitle(InternationalString collectiveTitle) {
    this.collectiveTitle = collectiveTitle;
  }

  public Citation isbn(String isbn) {
    this.isbn = isbn;
    return this;
  }

   /**
   * Get isbn
   * @return isbn
  **/
  @ApiModelProperty(value = "")
  public String getIsbn() {
    return isbn;
  }

  public void setIsbn(String isbn) {
    this.isbn = isbn;
  }

  public Citation issn(String issn) {
    this.issn = issn;
    return this;
  }

   /**
   * Get issn
   * @return issn
  **/
  @ApiModelProperty(value = "")
  public String getIssn() {
    return issn;
  }

  public void setIssn(String issn) {
    this.issn = issn;
  }

  public Citation dates(List<CitationDate> dates) {
    this.dates = dates;
    return this;
  }

  public Citation addDatesItem(CitationDate datesItem) {
    if (this.dates == null) {
      this.dates = new ArrayList<CitationDate>();
    }
    this.dates.add(datesItem);
    return this;
  }

   /**
   * Get dates
   * @return dates
  **/
  @ApiModelProperty(value = "")
  public List<CitationDate> getDates() {
    return dates;
  }

  public void setDates(List<CitationDate> dates) {
    this.dates = dates;
  }

  public Citation edition(InternationalString edition) {
    this.edition = edition;
    return this;
  }

   /**
   * Get edition
   * @return edition
  **/
  @ApiModelProperty(value = "")
  public InternationalString getEdition() {
    return edition;
  }

  public void setEdition(InternationalString edition) {
    this.edition = edition;
  }

  public Citation editionDate(OffsetDateTime editionDate) {
    this.editionDate = editionDate;
    return this;
  }

   /**
   * Get editionDate
   * @return editionDate
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getEditionDate() {
    return editionDate;
  }

  public void setEditionDate(OffsetDateTime editionDate) {
    this.editionDate = editionDate;
  }

  public Citation citedResponsibleParties(List<ResponsibleParty> citedResponsibleParties) {
    this.citedResponsibleParties = citedResponsibleParties;
    return this;
  }

  public Citation addCitedResponsiblePartiesItem(ResponsibleParty citedResponsiblePartiesItem) {
    if (this.citedResponsibleParties == null) {
      this.citedResponsibleParties = new ArrayList<ResponsibleParty>();
    }
    this.citedResponsibleParties.add(citedResponsiblePartiesItem);
    return this;
  }

   /**
   * Get citedResponsibleParties
   * @return citedResponsibleParties
  **/
  @ApiModelProperty(value = "")
  public List<ResponsibleParty> getCitedResponsibleParties() {
    return citedResponsibleParties;
  }

  public void setCitedResponsibleParties(List<ResponsibleParty> citedResponsibleParties) {
    this.citedResponsibleParties = citedResponsibleParties;
  }

  public Citation presentationForm(List<PresentationForm> presentationForm) {
    this.presentationForm = presentationForm;
    return this;
  }

  public Citation addPresentationFormItem(PresentationForm presentationFormItem) {
    if (this.presentationForm == null) {
      this.presentationForm = new ArrayList<PresentationForm>();
    }
    this.presentationForm.add(presentationFormItem);
    return this;
  }

   /**
   * Get presentationForm
   * @return presentationForm
  **/
  @ApiModelProperty(value = "")
  public List<PresentationForm> getPresentationForm() {
    return presentationForm;
  }

  public void setPresentationForm(List<PresentationForm> presentationForm) {
    this.presentationForm = presentationForm;
  }

  public Citation alternateTitles(List<InternationalString> alternateTitles) {
    this.alternateTitles = alternateTitles;
    return this;
  }

  public Citation addAlternateTitlesItem(InternationalString alternateTitlesItem) {
    if (this.alternateTitles == null) {
      this.alternateTitles = new ArrayList<InternationalString>();
    }
    this.alternateTitles.add(alternateTitlesItem);
    return this;
  }

   /**
   * Get alternateTitles
   * @return alternateTitles
  **/
  @ApiModelProperty(value = "")
  public List<InternationalString> getAlternateTitles() {
    return alternateTitles;
  }

  public void setAlternateTitles(List<InternationalString> alternateTitles) {
    this.alternateTitles = alternateTitles;
  }

  public Citation identifiers(List<Identifier> identifiers) {
    this.identifiers = identifiers;
    return this;
  }

  public Citation addIdentifiersItem(Identifier identifiersItem) {
    if (this.identifiers == null) {
      this.identifiers = new ArrayList<Identifier>();
    }
    this.identifiers.add(identifiersItem);
    return this;
  }

   /**
   * Get identifiers
   * @return identifiers
  **/
  @ApiModelProperty(value = "")
  public List<Identifier> getIdentifiers() {
    return identifiers;
  }

  public void setIdentifiers(List<Identifier> identifiers) {
    this.identifiers = identifiers;
  }

  public Citation title(InternationalString title) {
    this.title = title;
    return this;
  }

   /**
   * Get title
   * @return title
  **/
  @ApiModelProperty(value = "")
  public InternationalString getTitle() {
    return title;
  }

  public void setTitle(InternationalString title) {
    this.title = title;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Citation citation = (Citation) o;
    return Objects.equals(this.series, citation.series) &&
        Objects.equals(this.otherCitationDetails, citation.otherCitationDetails) &&
        Objects.equals(this.collectiveTitle, citation.collectiveTitle) &&
        Objects.equals(this.isbn, citation.isbn) &&
        Objects.equals(this.issn, citation.issn) &&
        Objects.equals(this.dates, citation.dates) &&
        Objects.equals(this.edition, citation.edition) &&
        Objects.equals(this.editionDate, citation.editionDate) &&
        Objects.equals(this.citedResponsibleParties, citation.citedResponsibleParties) &&
        Objects.equals(this.presentationForm, citation.presentationForm) &&
        Objects.equals(this.alternateTitles, citation.alternateTitles) &&
        Objects.equals(this.identifiers, citation.identifiers) &&
        Objects.equals(this.title, citation.title);
  }

  @Override
  public int hashCode() {
    return Objects.hash(series, otherCitationDetails, collectiveTitle, isbn, issn, dates, edition, editionDate, citedResponsibleParties, presentationForm, alternateTitles, identifiers, title);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Citation {\n");

    sb.append("    series: ").append(toIndentedString(series)).append("\n");
    sb.append("    otherCitationDetails: ").append(toIndentedString(otherCitationDetails)).append("\n");
    sb.append("    collectiveTitle: ").append(toIndentedString(collectiveTitle)).append("\n");
    sb.append("    isbn: ").append(toIndentedString(isbn)).append("\n");
    sb.append("    issn: ").append(toIndentedString(issn)).append("\n");
    sb.append("    dates: ").append(toIndentedString(dates)).append("\n");
    sb.append("    edition: ").append(toIndentedString(edition)).append("\n");
    sb.append("    editionDate: ").append(toIndentedString(editionDate)).append("\n");
    sb.append("    citedResponsibleParties: ").append(toIndentedString(citedResponsibleParties)).append("\n");
    sb.append("    presentationForm: ").append(toIndentedString(presentationForm)).append("\n");
    sb.append("    alternateTitles: ").append(toIndentedString(alternateTitles)).append("\n");
    sb.append("    identifiers: ").append(toIndentedString(identifiers)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}