/*-
 * ========================LICENSE_START=================================
 * 
 * Copyright (C) 2025 Regione Piemonte
 * 
 * SPDX-FileCopyrightText: (C) Copyright 2025 Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/*
 * ricerca-fulltext-geografica
 * Servizi di ricerca full text con localizzazione geografica
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.csi.scriva.scrivabesrv.business.be.helper.loccsi.dto;

import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * FeatureId
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-02-24T08:29:11.008Z")
public class FeatureId {
  private String featureVersion = null;

  private String rid = null;

  private String previousRid = null;

  private String id = null;

  public FeatureId featureVersion(String featureVersion) {
    this.featureVersion = featureVersion;
    return this;
  }

   /**
   * Get featureVersion
   * @return featureVersion
  **/
  @ApiModelProperty(value = "")
  public String getFeatureVersion() {
    return featureVersion;
  }

  public void setFeatureVersion(String featureVersion) {
    this.featureVersion = featureVersion;
  }

  public FeatureId rid(String rid) {
    this.rid = rid;
    return this;
  }

   /**
   * Get rid
   * @return rid
  **/
  @ApiModelProperty(value = "")
  public String getRid() {
    return rid;
  }

  public void setRid(String rid) {
    this.rid = rid;
  }

  public FeatureId previousRid(String previousRid) {
    this.previousRid = previousRid;
    return this;
  }

   /**
   * Get previousRid
   * @return previousRid
  **/
  @ApiModelProperty(value = "")
  public String getPreviousRid() {
    return previousRid;
  }

  public void setPreviousRid(String previousRid) {
    this.previousRid = previousRid;
  }

  public FeatureId id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FeatureId featureId = (FeatureId) o;
    return Objects.equals(this.featureVersion, featureId.featureVersion) &&
        Objects.equals(this.rid, featureId.rid) &&
        Objects.equals(this.previousRid, featureId.previousRid) &&
        Objects.equals(this.id, featureId.id);
  }

  @Override
  public int hashCode() {
    return Objects.hash(featureVersion, rid, previousRid, id);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FeatureId {\n");

    sb.append("    featureVersion: ").append(toIndentedString(featureVersion)).append("\n");
    sb.append("    rid: ").append(toIndentedString(rid)).append("\n");
    sb.append("    previousRid: ").append(toIndentedString(previousRid)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}