/*-
 * ========================LICENSE_START=================================
 * 
 * Copyright (C) 2025 Regione Piemonte
 * 
 * SPDX-FileCopyrightText: (C) Copyright 2025 Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/*
 * ricerca-fulltext-geografica
 * Servizi di ricerca full text con localizzazione geografica
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.csi.scriva.scrivabesrv.business.be.helper.loccsi.dto;

import io.swagger.annotations.ApiModelProperty;

import java.util.HashMap;
import java.util.Map;
import java.util.Objects;

/**
 * PropertyDescriptor
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-02-24T08:29:11.008Z")
public class PropertyDescriptor {
  private Boolean nillable = null;

  private Integer minOccurs = null;

  private Integer maxOccurs = null;

  private Map<String, Object> userData = null;

  private Name name = null;

  private PropertyType type = null;

  public PropertyDescriptor nillable(Boolean nillable) {
    this.nillable = nillable;
    return this;
  }

   /**
   * Get nillable
   * @return nillable
  **/
  @ApiModelProperty(value = "")
  public Boolean isNillable() {
    return nillable;
  }

  public void setNillable(Boolean nillable) {
    this.nillable = nillable;
  }

  public PropertyDescriptor minOccurs(Integer minOccurs) {
    this.minOccurs = minOccurs;
    return this;
  }

   /**
   * Get minOccurs
   * @return minOccurs
  **/
  @ApiModelProperty(value = "")
  public Integer getMinOccurs() {
    return minOccurs;
  }

  public void setMinOccurs(Integer minOccurs) {
    this.minOccurs = minOccurs;
  }

  public PropertyDescriptor maxOccurs(Integer maxOccurs) {
    this.maxOccurs = maxOccurs;
    return this;
  }

   /**
   * Get maxOccurs
   * @return maxOccurs
  **/
  @ApiModelProperty(value = "")
  public Integer getMaxOccurs() {
    return maxOccurs;
  }

  public void setMaxOccurs(Integer maxOccurs) {
    this.maxOccurs = maxOccurs;
  }

  public PropertyDescriptor userData(Map<String, Object> userData) {
    this.userData = userData;
    return this;
  }

  public PropertyDescriptor putUserDataItem(String key, Object userDataItem) {
    if (this.userData == null) {
      this.userData = new HashMap<String, Object>();
    }
    this.userData.put(key, userDataItem);
    return this;
  }

   /**
   * Get userData
   * @return userData
  **/
  @ApiModelProperty(value = "")
  public Map<String, Object> getUserData() {
    return userData;
  }

  public void setUserData(Map<String, Object> userData) {
    this.userData = userData;
  }

  public PropertyDescriptor name(Name name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public Name getName() {
    return name;
  }

  public void setName(Name name) {
    this.name = name;
  }

  public PropertyDescriptor type(PropertyType type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(value = "")
  public PropertyType getType() {
    return type;
  }

  public void setType(PropertyType type) {
    this.type = type;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PropertyDescriptor propertyDescriptor = (PropertyDescriptor) o;
    return Objects.equals(this.nillable, propertyDescriptor.nillable) &&
        Objects.equals(this.minOccurs, propertyDescriptor.minOccurs) &&
        Objects.equals(this.maxOccurs, propertyDescriptor.maxOccurs) &&
        Objects.equals(this.userData, propertyDescriptor.userData) &&
        Objects.equals(this.name, propertyDescriptor.name) &&
        Objects.equals(this.type, propertyDescriptor.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nillable, minOccurs, maxOccurs, userData, name, type);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PropertyDescriptor {\n");

    sb.append("    nillable: ").append(toIndentedString(nillable)).append("\n");
    sb.append("    minOccurs: ").append(toIndentedString(minOccurs)).append("\n");
    sb.append("    maxOccurs: ").append(toIndentedString(maxOccurs)).append("\n");
    sb.append("    userData: ").append(toIndentedString(userData)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}