/*-
 * ========================LICENSE_START=================================
 * 
 * Copyright (C) 2025 Regione Piemonte
 * 
 * SPDX-FileCopyrightText: (C) Copyright 2025 Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/*
 * ricerca-fulltext-geografica
 * Servizi di ricerca full text con localizzazione geografica
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.csi.scriva.scrivabesrv.business.be.helper.loccsi.dto;

import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

/**
 * PropertyType
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-02-24T08:29:11.008Z")
public class PropertyType {
  private PropertyType _super = null;

  private List<Filter> restrictions = null;

  private Map<String, Object> userData = null;

  private InternationalString description = null;

  private Name name = null;

  private Boolean _abstract = null;

  public PropertyType _super(PropertyType _super) {
    this._super = _super;
    return this;
  }

   /**
   * Get _super
   * @return _super
  **/
  @ApiModelProperty(value = "")
  public PropertyType getSuper() {
    return _super;
  }

  public void setSuper(PropertyType _super) {
    this._super = _super;
  }

  public PropertyType restrictions(List<Filter> restrictions) {
    this.restrictions = restrictions;
    return this;
  }

  public PropertyType addRestrictionsItem(Filter restrictionsItem) {
    if (this.restrictions == null) {
      this.restrictions = new ArrayList<Filter>();
    }
    this.restrictions.add(restrictionsItem);
    return this;
  }

   /**
   * Get restrictions
   * @return restrictions
  **/
  @ApiModelProperty(value = "")
  public List<Filter> getRestrictions() {
    return restrictions;
  }

  public void setRestrictions(List<Filter> restrictions) {
    this.restrictions = restrictions;
  }

  public PropertyType userData(Map<String, Object> userData) {
    this.userData = userData;
    return this;
  }

  public PropertyType putUserDataItem(String key, Object userDataItem) {
    if (this.userData == null) {
      this.userData = new HashMap<String, Object>();
    }
    this.userData.put(key, userDataItem);
    return this;
  }

   /**
   * Get userData
   * @return userData
  **/
  @ApiModelProperty(value = "")
  public Map<String, Object> getUserData() {
    return userData;
  }

  public void setUserData(Map<String, Object> userData) {
    this.userData = userData;
  }

  public PropertyType description(InternationalString description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(value = "")
  public InternationalString getDescription() {
    return description;
  }

  public void setDescription(InternationalString description) {
    this.description = description;
  }

  public PropertyType name(Name name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public Name getName() {
    return name;
  }

  public void setName(Name name) {
    this.name = name;
  }

  public PropertyType _abstract(Boolean _abstract) {
    this._abstract = _abstract;
    return this;
  }

   /**
   * Get _abstract
   * @return _abstract
  **/
  @ApiModelProperty(value = "")
  public Boolean isAbstract() {
    return _abstract;
  }

  public void setAbstract(Boolean _abstract) {
    this._abstract = _abstract;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PropertyType propertyType = (PropertyType) o;
    return Objects.equals(this._super, propertyType._super) &&
        Objects.equals(this.restrictions, propertyType.restrictions) &&
        Objects.equals(this.userData, propertyType.userData) &&
        Objects.equals(this.description, propertyType.description) &&
        Objects.equals(this.name, propertyType.name) &&
        Objects.equals(this._abstract, propertyType._abstract);
  }

  @Override
  public int hashCode() {
    return Objects.hash(_super, restrictions, userData, description, name, _abstract);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PropertyType {\n");

    sb.append("    _super: ").append(toIndentedString(_super)).append("\n");
    sb.append("    restrictions: ").append(toIndentedString(restrictions)).append("\n");
    sb.append("    userData: ").append(toIndentedString(userData)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    _abstract: ").append(toIndentedString(_abstract)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}