/*-
 * ========================LICENSE_START=================================
 * 
 * Copyright (C) 2025 Regione Piemonte
 * 
 * SPDX-FileCopyrightText: (C) Copyright 2025 Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/*
 * ricerca-fulltext-geografica
 * Servizi di ricerca full text con localizzazione geografica
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.csi.scriva.scrivabesrv.business.be.helper.loccsi.dto;

import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * ReferenceIdentifier
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-02-24T08:29:11.008Z")
public class ReferenceIdentifier {
  private String codeSpace = null;

  private String version = null;

  private String code = null;

  private Citation authority = null;

  public ReferenceIdentifier codeSpace(String codeSpace) {
    this.codeSpace = codeSpace;
    return this;
  }

   /**
   * Get codeSpace
   * @return codeSpace
  **/
  @ApiModelProperty(value = "")
  public String getCodeSpace() {
    return codeSpace;
  }

  public void setCodeSpace(String codeSpace) {
    this.codeSpace = codeSpace;
  }

  public ReferenceIdentifier version(String version) {
    this.version = version;
    return this;
  }

   /**
   * Get version
   * @return version
  **/
  @ApiModelProperty(value = "")
  public String getVersion() {
    return version;
  }

  public void setVersion(String version) {
    this.version = version;
  }

  public ReferenceIdentifier code(String code) {
    this.code = code;
    return this;
  }

   /**
   * Get code
   * @return code
  **/
  @ApiModelProperty(value = "")
  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public ReferenceIdentifier authority(Citation authority) {
    this.authority = authority;
    return this;
  }

   /**
   * Get authority
   * @return authority
  **/
  @ApiModelProperty(value = "")
  public Citation getAuthority() {
    return authority;
  }

  public void setAuthority(Citation authority) {
    this.authority = authority;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReferenceIdentifier referenceIdentifier = (ReferenceIdentifier) o;
    return Objects.equals(this.codeSpace, referenceIdentifier.codeSpace) &&
        Objects.equals(this.version, referenceIdentifier.version) &&
        Objects.equals(this.code, referenceIdentifier.code) &&
        Objects.equals(this.authority, referenceIdentifier.authority);
  }

  @Override
  public int hashCode() {
    return Objects.hash(codeSpace, version, code, authority);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReferenceIdentifier {\n");

    sb.append("    codeSpace: ").append(toIndentedString(codeSpace)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    authority: ").append(toIndentedString(authority)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}