/*-
 * ========================LICENSE_START=================================
 * 
 * Copyright (C) 2025 Regione Piemonte
 * 
 * SPDX-FileCopyrightText: (C) Copyright 2025 Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/*
 * ricerca-fulltext-geografica
 * Servizi di ricerca full text con localizzazione geografica
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.csi.scriva.scrivabesrv.business.be.helper.loccsi.dto;

import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * ResponsibleParty
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-02-24T08:29:11.008Z")
public class ResponsibleParty {
  private String individualName = null;

  private InternationalString organisationName = null;

  private InternationalString positionName = null;

  private Contact contactInfo = null;

  private Role role = null;

  public ResponsibleParty individualName(String individualName) {
    this.individualName = individualName;
    return this;
  }

   /**
   * Get individualName
   * @return individualName
  **/
  @ApiModelProperty(value = "")
  public String getIndividualName() {
    return individualName;
  }

  public void setIndividualName(String individualName) {
    this.individualName = individualName;
  }

  public ResponsibleParty organisationName(InternationalString organisationName) {
    this.organisationName = organisationName;
    return this;
  }

   /**
   * Get organisationName
   * @return organisationName
  **/
  @ApiModelProperty(value = "")
  public InternationalString getOrganisationName() {
    return organisationName;
  }

  public void setOrganisationName(InternationalString organisationName) {
    this.organisationName = organisationName;
  }

  public ResponsibleParty positionName(InternationalString positionName) {
    this.positionName = positionName;
    return this;
  }

   /**
   * Get positionName
   * @return positionName
  **/
  @ApiModelProperty(value = "")
  public InternationalString getPositionName() {
    return positionName;
  }

  public void setPositionName(InternationalString positionName) {
    this.positionName = positionName;
  }

  public ResponsibleParty contactInfo(Contact contactInfo) {
    this.contactInfo = contactInfo;
    return this;
  }

   /**
   * Get contactInfo
   * @return contactInfo
  **/
  @ApiModelProperty(value = "")
  public Contact getContactInfo() {
    return contactInfo;
  }

  public void setContactInfo(Contact contactInfo) {
    this.contactInfo = contactInfo;
  }

  public ResponsibleParty role(Role role) {
    this.role = role;
    return this;
  }

   /**
   * Get role
   * @return role
  **/
  @ApiModelProperty(value = "")
  public Role getRole() {
    return role;
  }

  public void setRole(Role role) {
    this.role = role;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponsibleParty responsibleParty = (ResponsibleParty) o;
    return Objects.equals(this.individualName, responsibleParty.individualName) &&
        Objects.equals(this.organisationName, responsibleParty.organisationName) &&
        Objects.equals(this.positionName, responsibleParty.positionName) &&
        Objects.equals(this.contactInfo, responsibleParty.contactInfo) &&
        Objects.equals(this.role, responsibleParty.role);
  }

  @Override
  public int hashCode() {
    return Objects.hash(individualName, organisationName, positionName, contactInfo, role);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponsibleParty {\n");

    sb.append("    individualName: ").append(toIndentedString(individualName)).append("\n");
    sb.append("    organisationName: ").append(toIndentedString(organisationName)).append("\n");
    sb.append("    positionName: ").append(toIndentedString(positionName)).append("\n");
    sb.append("    contactInfo: ").append(toIndentedString(contactInfo)).append("\n");
    sb.append("    role: ").append(toIndentedString(role)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}