/*-
 * ========================LICENSE_START=================================
 * 
 * Copyright (C) 2025 Regione Piemonte
 * 
 * SPDX-FileCopyrightText: (C) Copyright 2025 Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/*
 * ricerca-fulltext-geografica
 * Servizi di ricerca full text con localizzazione geografica
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.csi.scriva.scrivabesrv.business.be.helper.loccsi.dto;

import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * Series
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-02-24T08:29:11.008Z")
public class Series {
  private String issueIdentification = null;

  private String page = null;

  private InternationalString name = null;

  public Series issueIdentification(String issueIdentification) {
    this.issueIdentification = issueIdentification;
    return this;
  }

   /**
   * Get issueIdentification
   * @return issueIdentification
  **/
  @ApiModelProperty(value = "")
  public String getIssueIdentification() {
    return issueIdentification;
  }

  public void setIssueIdentification(String issueIdentification) {
    this.issueIdentification = issueIdentification;
  }

  public Series page(String page) {
    this.page = page;
    return this;
  }

   /**
   * Get page
   * @return page
  **/
  @ApiModelProperty(value = "")
  public String getPage() {
    return page;
  }

  public void setPage(String page) {
    this.page = page;
  }

  public Series name(InternationalString name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public InternationalString getName() {
    return name;
  }

  public void setName(InternationalString name) {
    this.name = name;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Series series = (Series) o;
    return Objects.equals(this.issueIdentification, series.issueIdentification) &&
        Objects.equals(this.page, series.page) &&
        Objects.equals(this.name, series.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(issueIdentification, page, name);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Series {\n");

    sb.append("    issueIdentification: ").append(toIndentedString(issueIdentification)).append("\n");
    sb.append("    page: ").append(toIndentedString(page)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}