/*-
 * ========================LICENSE_START=================================
 * 
 * Copyright (C) 2025 Regione Piemonte
 * 
 * SPDX-FileCopyrightText: (C) Copyright 2025 Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/*
 * ricerca-fulltext-geografica
 * Servizi di ricerca full text con localizzazione geografica
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.csi.scriva.scrivabesrv.business.be.helper.loccsi.dto;

import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Telephone
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-02-24T08:29:11.008Z")
public class Telephone {
  private List<String> voices = null;

  private List<String> facsimiles = null;

  public Telephone voices(List<String> voices) {
    this.voices = voices;
    return this;
  }

  public Telephone addVoicesItem(String voicesItem) {
    if (this.voices == null) {
      this.voices = new ArrayList<String>();
    }
    this.voices.add(voicesItem);
    return this;
  }

   /**
   * Get voices
   * @return voices
  **/
  @ApiModelProperty(value = "")
  public List<String> getVoices() {
    return voices;
  }

  public void setVoices(List<String> voices) {
    this.voices = voices;
  }

  public Telephone facsimiles(List<String> facsimiles) {
    this.facsimiles = facsimiles;
    return this;
  }

  public Telephone addFacsimilesItem(String facsimilesItem) {
    if (this.facsimiles == null) {
      this.facsimiles = new ArrayList<String>();
    }
    this.facsimiles.add(facsimilesItem);
    return this;
  }

   /**
   * Get facsimiles
   * @return facsimiles
  **/
  @ApiModelProperty(value = "")
  public List<String> getFacsimiles() {
    return facsimiles;
  }

  public void setFacsimiles(List<String> facsimiles) {
    this.facsimiles = facsimiles;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Telephone telephone = (Telephone) o;
    return Objects.equals(this.voices, telephone.voices) &&
        Objects.equals(this.facsimiles, telephone.facsimiles);
  }

  @Override
  public int hashCode() {
    return Objects.hash(voices, facsimiles);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Telephone {\n");

    sb.append("    voices: ").append(toIndentedString(voices)).append("\n");
    sb.append("    facsimiles: ").append(toIndentedString(facsimiles)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}