/*-
 * ========================LICENSE_START=================================
 * 
 * Copyright (C) 2025 Regione Piemonte
 * 
 * SPDX-FileCopyrightText: (C) Copyright 2025 Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/*
 * ricerca-fulltext-geografica
 * Servizi di ricerca full text con localizzazione geografica
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.csi.scriva.scrivabesrv.business.be.helper.loccsi.dto;

import io.swagger.annotations.ApiModelProperty;

import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * VerticalDatum
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-02-24T08:29:11.008Z")
public class VerticalDatum {
  private VerticalDatumType verticalDatumType = null;

  private Extent domainOfValidity = null;

  private InternationalString anchorPoint = null;

  private OffsetDateTime realizationEpoch = null;

  private InternationalString scope = null;

  private List<GenericName> alias = null;

  private InternationalString remarks = null;

  private List<ReferenceIdentifier> identifiers = null;

  private ReferenceIdentifier name = null;

  public VerticalDatum verticalDatumType(VerticalDatumType verticalDatumType) {
    this.verticalDatumType = verticalDatumType;
    return this;
  }

   /**
   * Get verticalDatumType
   * @return verticalDatumType
  **/
  @ApiModelProperty(value = "")
  public VerticalDatumType getVerticalDatumType() {
    return verticalDatumType;
  }

  public void setVerticalDatumType(VerticalDatumType verticalDatumType) {
    this.verticalDatumType = verticalDatumType;
  }

  public VerticalDatum domainOfValidity(Extent domainOfValidity) {
    this.domainOfValidity = domainOfValidity;
    return this;
  }

   /**
   * Get domainOfValidity
   * @return domainOfValidity
  **/
  @ApiModelProperty(value = "")
  public Extent getDomainOfValidity() {
    return domainOfValidity;
  }

  public void setDomainOfValidity(Extent domainOfValidity) {
    this.domainOfValidity = domainOfValidity;
  }

  public VerticalDatum anchorPoint(InternationalString anchorPoint) {
    this.anchorPoint = anchorPoint;
    return this;
  }

   /**
   * Get anchorPoint
   * @return anchorPoint
  **/
  @ApiModelProperty(value = "")
  public InternationalString getAnchorPoint() {
    return anchorPoint;
  }

  public void setAnchorPoint(InternationalString anchorPoint) {
    this.anchorPoint = anchorPoint;
  }

  public VerticalDatum realizationEpoch(OffsetDateTime realizationEpoch) {
    this.realizationEpoch = realizationEpoch;
    return this;
  }

   /**
   * Get realizationEpoch
   * @return realizationEpoch
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getRealizationEpoch() {
    return realizationEpoch;
  }

  public void setRealizationEpoch(OffsetDateTime realizationEpoch) {
    this.realizationEpoch = realizationEpoch;
  }

  public VerticalDatum scope(InternationalString scope) {
    this.scope = scope;
    return this;
  }

   /**
   * Get scope
   * @return scope
  **/
  @ApiModelProperty(value = "")
  public InternationalString getScope() {
    return scope;
  }

  public void setScope(InternationalString scope) {
    this.scope = scope;
  }

  public VerticalDatum alias(List<GenericName> alias) {
    this.alias = alias;
    return this;
  }

  public VerticalDatum addAliasItem(GenericName aliasItem) {
    if (this.alias == null) {
      this.alias = new ArrayList<GenericName>();
    }
    this.alias.add(aliasItem);
    return this;
  }

   /**
   * Get alias
   * @return alias
  **/
  @ApiModelProperty(value = "")
  public List<GenericName> getAlias() {
    return alias;
  }

  public void setAlias(List<GenericName> alias) {
    this.alias = alias;
  }

  public VerticalDatum remarks(InternationalString remarks) {
    this.remarks = remarks;
    return this;
  }

   /**
   * Get remarks
   * @return remarks
  **/
  @ApiModelProperty(value = "")
  public InternationalString getRemarks() {
    return remarks;
  }

  public void setRemarks(InternationalString remarks) {
    this.remarks = remarks;
  }

  public VerticalDatum identifiers(List<ReferenceIdentifier> identifiers) {
    this.identifiers = identifiers;
    return this;
  }

  public VerticalDatum addIdentifiersItem(ReferenceIdentifier identifiersItem) {
    if (this.identifiers == null) {
      this.identifiers = new ArrayList<ReferenceIdentifier>();
    }
    this.identifiers.add(identifiersItem);
    return this;
  }

   /**
   * Get identifiers
   * @return identifiers
  **/
  @ApiModelProperty(value = "")
  public List<ReferenceIdentifier> getIdentifiers() {
    return identifiers;
  }

  public void setIdentifiers(List<ReferenceIdentifier> identifiers) {
    this.identifiers = identifiers;
  }

  public VerticalDatum name(ReferenceIdentifier name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public ReferenceIdentifier getName() {
    return name;
  }

  public void setName(ReferenceIdentifier name) {
    this.name = name;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VerticalDatum verticalDatum = (VerticalDatum) o;
    return Objects.equals(this.verticalDatumType, verticalDatum.verticalDatumType) &&
        Objects.equals(this.domainOfValidity, verticalDatum.domainOfValidity) &&
        Objects.equals(this.anchorPoint, verticalDatum.anchorPoint) &&
        Objects.equals(this.realizationEpoch, verticalDatum.realizationEpoch) &&
        Objects.equals(this.scope, verticalDatum.scope) &&
        Objects.equals(this.alias, verticalDatum.alias) &&
        Objects.equals(this.remarks, verticalDatum.remarks) &&
        Objects.equals(this.identifiers, verticalDatum.identifiers) &&
        Objects.equals(this.name, verticalDatum.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(verticalDatumType, domainOfValidity, anchorPoint, realizationEpoch, scope, alias, remarks, identifiers, name);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VerticalDatum {\n");

    sb.append("    verticalDatumType: ").append(toIndentedString(verticalDatumType)).append("\n");
    sb.append("    domainOfValidity: ").append(toIndentedString(domainOfValidity)).append("\n");
    sb.append("    anchorPoint: ").append(toIndentedString(anchorPoint)).append("\n");
    sb.append("    realizationEpoch: ").append(toIndentedString(realizationEpoch)).append("\n");
    sb.append("    scope: ").append(toIndentedString(scope)).append("\n");
    sb.append("    alias: ").append(toIndentedString(alias)).append("\n");
    sb.append("    remarks: ").append(toIndentedString(remarks)).append("\n");
    sb.append("    identifiers: ").append(toIndentedString(identifiers)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}