/*-
 * ========================LICENSE_START=================================
 * 
 * Copyright (C) 2025 Regione Piemonte
 * 
 * SPDX-FileCopyrightText: (C) Copyright 2025 Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/*
 * ricerca-fulltext-geografica
 * Servizi di ricerca full text con localizzazione geografica
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.csi.scriva.scrivabesrv.business.be.helper.loccsi.dto;

import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * VerticalCS
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-02-24T08:29:11.008Z")
public class VerticalCS {
  private Integer dimension = null;

  private List<GenericName> alias = null;

  private InternationalString remarks = null;

  private List<ReferenceIdentifier> identifiers = null;

  private ReferenceIdentifier name = null;

  public VerticalCS dimension(Integer dimension) {
    this.dimension = dimension;
    return this;
  }

   /**
   * Get dimension
   * @return dimension
  **/
  @ApiModelProperty(value = "")
  public Integer getDimension() {
    return dimension;
  }

  public void setDimension(Integer dimension) {
    this.dimension = dimension;
  }

  public VerticalCS alias(List<GenericName> alias) {
    this.alias = alias;
    return this;
  }

  public VerticalCS addAliasItem(GenericName aliasItem) {
    if (this.alias == null) {
      this.alias = new ArrayList<GenericName>();
    }
    this.alias.add(aliasItem);
    return this;
  }

   /**
   * Get alias
   * @return alias
  **/
  @ApiModelProperty(value = "")
  public List<GenericName> getAlias() {
    return alias;
  }

  public void setAlias(List<GenericName> alias) {
    this.alias = alias;
  }

  public VerticalCS remarks(InternationalString remarks) {
    this.remarks = remarks;
    return this;
  }

   /**
   * Get remarks
   * @return remarks
  **/
  @ApiModelProperty(value = "")
  public InternationalString getRemarks() {
    return remarks;
  }

  public void setRemarks(InternationalString remarks) {
    this.remarks = remarks;
  }

  public VerticalCS identifiers(List<ReferenceIdentifier> identifiers) {
    this.identifiers = identifiers;
    return this;
  }

  public VerticalCS addIdentifiersItem(ReferenceIdentifier identifiersItem) {
    if (this.identifiers == null) {
      this.identifiers = new ArrayList<ReferenceIdentifier>();
    }
    this.identifiers.add(identifiersItem);
    return this;
  }

   /**
   * Get identifiers
   * @return identifiers
  **/
  @ApiModelProperty(value = "")
  public List<ReferenceIdentifier> getIdentifiers() {
    return identifiers;
  }

  public void setIdentifiers(List<ReferenceIdentifier> identifiers) {
    this.identifiers = identifiers;
  }

  public VerticalCS name(ReferenceIdentifier name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public ReferenceIdentifier getName() {
    return name;
  }

  public void setName(ReferenceIdentifier name) {
    this.name = name;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VerticalCS verticalCS = (VerticalCS) o;
    return Objects.equals(this.dimension, verticalCS.dimension) &&
        Objects.equals(this.alias, verticalCS.alias) &&
        Objects.equals(this.remarks, verticalCS.remarks) &&
        Objects.equals(this.identifiers, verticalCS.identifiers) &&
        Objects.equals(this.name, verticalCS.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dimension, alias, remarks, identifiers, name);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VerticalCS {\n");

    sb.append("    dimension: ").append(toIndentedString(dimension)).append("\n");
    sb.append("    alias: ").append(toIndentedString(alias)).append("\n");
    sb.append("    remarks: ").append(toIndentedString(remarks)).append("\n");
    sb.append("    identifiers: ").append(toIndentedString(identifiers)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}