/*-
 * ========================LICENSE_START=================================
 * 
 * Copyright (C) 2025 Regione Piemonte
 * 
 * SPDX-FileCopyrightText: (C) Copyright 2025 Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/*
 * ricerca-fulltext-geografica
 * Servizi di ricerca full text con localizzazione geografica
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.csi.scriva.scrivabesrv.business.be.helper.loccsi.dto;

import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * VerticalExtent
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-02-24T08:29:11.008Z")
public class VerticalExtent {
  private Double minimumValue = null;

  private Double maximumValue = null;

  private VerticalCRS verticalCRS = null;

  public VerticalExtent minimumValue(Double minimumValue) {
    this.minimumValue = minimumValue;
    return this;
  }

   /**
   * Get minimumValue
   * @return minimumValue
  **/
  @ApiModelProperty(value = "")
  public Double getMinimumValue() {
    return minimumValue;
  }

  public void setMinimumValue(Double minimumValue) {
    this.minimumValue = minimumValue;
  }

  public VerticalExtent maximumValue(Double maximumValue) {
    this.maximumValue = maximumValue;
    return this;
  }

   /**
   * Get maximumValue
   * @return maximumValue
  **/
  @ApiModelProperty(value = "")
  public Double getMaximumValue() {
    return maximumValue;
  }

  public void setMaximumValue(Double maximumValue) {
    this.maximumValue = maximumValue;
  }

  public VerticalExtent verticalCRS(VerticalCRS verticalCRS) {
    this.verticalCRS = verticalCRS;
    return this;
  }

   /**
   * Get verticalCRS
   * @return verticalCRS
  **/
  @ApiModelProperty(value = "")
  public VerticalCRS getVerticalCRS() {
    return verticalCRS;
  }

  public void setVerticalCRS(VerticalCRS verticalCRS) {
    this.verticalCRS = verticalCRS;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VerticalExtent verticalExtent = (VerticalExtent) o;
    return Objects.equals(this.minimumValue, verticalExtent.minimumValue) &&
        Objects.equals(this.maximumValue, verticalExtent.maximumValue) &&
        Objects.equals(this.verticalCRS, verticalExtent.verticalCRS);
  }

  @Override
  public int hashCode() {
    return Objects.hash(minimumValue, maximumValue, verticalCRS);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VerticalExtent {\n");

    sb.append("    minimumValue: ").append(toIndentedString(minimumValue)).append("\n");
    sb.append("    maximumValue: ").append(toIndentedString(maximumValue)).append("\n");
    sb.append("    verticalCRS: ").append(toIndentedString(verticalCRS)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}