/*-
 * ========================LICENSE_START=================================
 * 
 * Copyright (C) 2025 Regione Piemonte
 * 
 * SPDX-FileCopyrightText: (C) Copyright 2025 Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/*
 * ECMEngine
 * Servizi di fruizione ECM INDEX.
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.csi.scriva.scrivabesrv.business.be.helper.index.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * Rappresenta una ACL. Una ACL permette di definire quale permesso è concesso o negato a una specifica autority. Un&#39;autority può essere un utente o un gruppo del tenant. I permessi possono essere:   &gt;       Consumer: lettura.     Editor: lettura e modifica.     Contributor: lettura e creazione.     Collaborator: lettura, modifica e creazione.    Si consiglia di utilizzare solo ACL permissive, in quanto il comportamento di default è remissivo (se non ci sono ACL impostate, l&#39;accesso viene negato).    Si ricorda che sulla company home del tenant /app:company_home è definita una ACL ereditata permissiva di tipo GROUP_EVERYONE - Consumer, che permette di default a tutti gli utenti di leggere tutto il contenuto del tenant: se questo non è il comportamento desiderato, è possibile rimuovere l&#39;ereditarietà della ACL con il servizio setInheritsAcl.    Le operazioni eseguite con l&#39;utente admin del tenant non sono sottoposte ad alcuna ACL.
 */
@ApiModel(description = "Rappresenta una ACL. Una ACL permette di definire quale permesso è concesso o negato a una specifica autority. Un'autority può essere un utente o un gruppo del tenant. I permessi possono essere:   >       Consumer: lettura.     Editor: lettura e modifica.     Contributor: lettura e creazione.     Collaborator: lettura, modifica e creazione.    Si consiglia di utilizzare solo ACL permissive, in quanto il comportamento di default è remissivo (se non ci sono ACL impostate, l'accesso viene negato).    Si ricorda che sulla company home del tenant /app:company_home è definita una ACL ereditata permissiva di tipo GROUP_EVERYONE - Consumer, che permette di default a tutti gli utenti di leggere tutto il contenuto del tenant: se questo non è il comportamento desiderato, è possibile rimuovere l'ereditarietà della ACL con il servizio setInheritsAcl.    Le operazioni eseguite con l'utente admin del tenant non sono sottoposte ad alcuna ACL. ")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-03-29T13:41:28.556Z")
@JsonInclude(JsonInclude.Include.NON_NULL)
public class AclRecord {
    @JsonProperty("authority")
    private String authority = null;

    @JsonProperty("permission")
    private String permission = null;

    @JsonProperty("accessAllowed")
    private Boolean accessAllowed = null;

    /**
     * Authority acl record.
     *
     * @param authority the authority
     * @return the acl record
     */
    public AclRecord authority(String authority) {
        this.authority = authority;
        return this;
    }

    /**
     * Rappresenta l&#39;autority.
     *
     * @return authority authority
     */
    @ApiModelProperty(example = "user", value = "Rappresenta l'autority.")
    public String getAuthority() {
        return authority;
    }

    /**
     * Sets authority.
     *
     * @param authority the authority
     */
    public void setAuthority(String authority) {
        this.authority = authority;
    }

    /**
     * Permission acl record.
     *
     * @param permission the permission
     * @return the acl record
     */
    public AclRecord permission(String permission) {
        this.permission = permission;
        return this;
    }

    /**
     * Rappresenta il permesso.
     *
     * @return permission permission
     */
    @ApiModelProperty(example = "Consumer", value = "Rappresenta il permesso.")
    public String getPermission() {
        return permission;
    }

    /**
     * Sets permission.
     *
     * @param permission the permission
     */
    public void setPermission(String permission) {
        this.permission = permission;
    }

    /**
     * Access allowed acl record.
     *
     * @param accessAllowed the access allowed
     * @return the acl record
     */
    public AclRecord accessAllowed(Boolean accessAllowed) {
        this.accessAllowed = accessAllowed;
        return this;
    }

    /**
     * Comportamento permissivo o remissivo dell&#39;ACL.
     *
     * @return accessAllowed boolean
     */
    @ApiModelProperty(value = "Comportamento permissivo o remissivo dell'ACL.")
    public Boolean isAccessAllowed() {
        return accessAllowed;
    }

    /**
     * Sets access allowed.
     *
     * @param accessAllowed the access allowed
     */
    public void setAccessAllowed(Boolean accessAllowed) {
        this.accessAllowed = accessAllowed;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        AclRecord aclRecord = (AclRecord) o;
        return Objects.equals(this.authority, aclRecord.authority) &&
                Objects.equals(this.permission, aclRecord.permission) &&
                Objects.equals(this.accessAllowed, aclRecord.accessAllowed);
    }

    @Override
    public int hashCode() {
        return Objects.hash(authority, permission, accessAllowed);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class AclRecord {\n");

        sb.append("    authority: ").append(toIndentedString(authority)).append("\n");
        sb.append("    permission: ").append(toIndentedString(permission)).append("\n");
        sb.append("    accessAllowed: ").append(toIndentedString(accessAllowed)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}