/*-
 * ========================LICENSE_START=================================
 * 
 * Copyright (C) 2025 Regione Piemonte
 * 
 * SPDX-FileCopyrightText: (C) Copyright 2025 Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/*
 * ECMEngine
 * Servizi di fruizione ECM INDEX.
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.csi.scriva.scrivabesrv.business.be.helper.index.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Definizione di un aspetto (aspect) del modello dei dati.
 */
@ApiModel(description = "Definizione di un aspetto (aspect) del modello dei dati.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-03-29T13:41:28.556Z")
@JsonInclude(JsonInclude.Include.NON_NULL)
public class AspectMetadata {
    @JsonProperty("prefixedName")
    private String prefixedName = null;

    @JsonProperty("title")
    private String title = null;

    @JsonProperty("description")
    private String description = null;

    @JsonProperty("modelDescriptor")
    private ModelDescriptor modelDescriptor = null;

    @JsonProperty("properties")
    private List<PropertyMetadata> properties = null;

    @JsonProperty("associations")
    private List<AssociationMetadata> associations = null;

    @JsonProperty("childAssociations")
    private List<AssociationMetadata> childAssociations = null;

    @JsonProperty("parentPrefixedName")
    private String parentPrefixedName = null;

    /**
     * Prefixed name aspect metadata.
     *
     * @param prefixedName the prefixed name
     * @return the aspect metadata
     */
    public AspectMetadata prefixedName(String prefixedName) {
        this.prefixedName = prefixedName;
        return this;
    }

    /**
     * Prefixed name dell&#39;elemento.
     *
     * @return prefixedName prefixed name
     */
    @ApiModelProperty(example = "sys:referenceable", value = "Prefixed name dell'elemento.")
    public String getPrefixedName() {
        return prefixedName;
    }

    /**
     * Sets prefixed name.
     *
     * @param prefixedName the prefixed name
     */
    public void setPrefixedName(String prefixedName) {
        this.prefixedName = prefixedName;
    }

    /**
     * Title aspect metadata.
     *
     * @param title the title
     * @return the aspect metadata
     */
    public AspectMetadata title(String title) {
        this.title = title;
        return this;
    }

    /**
     * Titolo dell&#39;elemento.
     *
     * @return title title
     */
    @ApiModelProperty(example = "Referenceable", value = "Titolo dell'elemento.")
    public String getTitle() {
        return title;
    }

    /**
     * Sets title.
     *
     * @param title the title
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * Description aspect metadata.
     *
     * @param description the description
     * @return the aspect metadata
     */
    public AspectMetadata description(String description) {
        this.description = description;
        return this;
    }

    /**
     * Descrizione dell&#39;elemento.
     *
     * @return description description
     */
    @ApiModelProperty(example = "Referenceable", value = "Descrizione dell'elemento.")
    public String getDescription() {
        return description;
    }

    /**
     * Sets description.
     *
     * @param description the description
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Model descriptor aspect metadata.
     *
     * @param modelDescriptor the model descriptor
     * @return the aspect metadata
     */
    public AspectMetadata modelDescriptor(ModelDescriptor modelDescriptor) {
        this.modelDescriptor = modelDescriptor;
        return this;
    }

    /**
     * Get modelDescriptor
     *
     * @return modelDescriptor model descriptor
     */
    @ApiModelProperty(value = "")
    public ModelDescriptor getModelDescriptor() {
        return modelDescriptor;
    }

    /**
     * Sets model descriptor.
     *
     * @param modelDescriptor the model descriptor
     */
    public void setModelDescriptor(ModelDescriptor modelDescriptor) {
        this.modelDescriptor = modelDescriptor;
    }

    /**
     * Properties aspect metadata.
     *
     * @param properties the properties
     * @return the aspect metadata
     */
    public AspectMetadata properties(List<PropertyMetadata> properties) {
        this.properties = properties;
        return this;
    }

    /**
     * Add properties item aspect metadata.
     *
     * @param propertiesItem the properties item
     * @return the aspect metadata
     */
    public AspectMetadata addPropertiesItem(PropertyMetadata propertiesItem) {
        if (this.properties == null) {
            this.properties = new ArrayList<PropertyMetadata>();
        }
        this.properties.add(propertiesItem);
        return this;
    }

    /**
     * Definizioni delle proprietà dell&#39;aspetto.
     *
     * @return properties properties
     */
    @ApiModelProperty(value = "Definizioni delle proprietà dell'aspetto.")
    public List<PropertyMetadata> getProperties() {
        return properties;
    }

    /**
     * Sets properties.
     *
     * @param properties the properties
     */
    public void setProperties(List<PropertyMetadata> properties) {
        this.properties = properties;
    }

    /**
     * Associations aspect metadata.
     *
     * @param associations the associations
     * @return the aspect metadata
     */
    public AspectMetadata associations(List<AssociationMetadata> associations) {
        this.associations = associations;
        return this;
    }

    /**
     * Add associations item aspect metadata.
     *
     * @param associationsItem the associations item
     * @return the aspect metadata
     */
    public AspectMetadata addAssociationsItem(AssociationMetadata associationsItem) {
        if (this.associations == null) {
            this.associations = new ArrayList<AssociationMetadata>();
        }
        this.associations.add(associationsItem);
        return this;
    }

    /**
     * definizioni delle associazioni sorgente-destinazione dell&#39;aspetto.
     *
     * @return associations associations
     */
    @ApiModelProperty(value = "definizioni delle associazioni sorgente-destinazione dell'aspetto.")
    public List<AssociationMetadata> getAssociations() {
        return associations;
    }

    /**
     * Sets associations.
     *
     * @param associations the associations
     */
    public void setAssociations(List<AssociationMetadata> associations) {
        this.associations = associations;
    }

    /**
     * Child associations aspect metadata.
     *
     * @param childAssociations the child associations
     * @return the aspect metadata
     */
    public AspectMetadata childAssociations(List<AssociationMetadata> childAssociations) {
        this.childAssociations = childAssociations;
        return this;
    }

    /**
     * Add child associations item aspect metadata.
     *
     * @param childAssociationsItem the child associations item
     * @return the aspect metadata
     */
    public AspectMetadata addChildAssociationsItem(AssociationMetadata childAssociationsItem) {
        if (this.childAssociations == null) {
            this.childAssociations = new ArrayList<AssociationMetadata>();
        }
        this.childAssociations.add(childAssociationsItem);
        return this;
    }

    /**
     * Definizioni delle associazioni padre-figlio dell&#39;aspetto.
     *
     * @return childAssociations child associations
     */
    @ApiModelProperty(value = "Definizioni delle associazioni padre-figlio dell'aspetto.")
    public List<AssociationMetadata> getChildAssociations() {
        return childAssociations;
    }

    /**
     * Sets child associations.
     *
     * @param childAssociations the child associations
     */
    public void setChildAssociations(List<AssociationMetadata> childAssociations) {
        this.childAssociations = childAssociations;
    }

    /**
     * Parent prefixed name aspect metadata.
     *
     * @param parentPrefixedName the parent prefixed name
     * @return the aspect metadata
     */
    public AspectMetadata parentPrefixedName(String parentPrefixedName) {
        this.parentPrefixedName = parentPrefixedName;
        return this;
    }

    /**
     * Prefixed name dell&#39;aspetto padre, se presente, altrimenti null.
     *
     * @return parentPrefixedName parent prefixed name
     */
    @ApiModelProperty(example = "cm:content", value = "Prefixed name dell'aspetto padre, se presente, altrimenti null.")
    public String getParentPrefixedName() {
        return parentPrefixedName;
    }

    /**
     * Sets parent prefixed name.
     *
     * @param parentPrefixedName the parent prefixed name
     */
    public void setParentPrefixedName(String parentPrefixedName) {
        this.parentPrefixedName = parentPrefixedName;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        AspectMetadata aspectMetadata = (AspectMetadata) o;
        return Objects.equals(this.prefixedName, aspectMetadata.prefixedName) &&
                Objects.equals(this.title, aspectMetadata.title) &&
                Objects.equals(this.description, aspectMetadata.description) &&
                Objects.equals(this.modelDescriptor, aspectMetadata.modelDescriptor) &&
                Objects.equals(this.properties, aspectMetadata.properties) &&
                Objects.equals(this.associations, aspectMetadata.associations) &&
                Objects.equals(this.childAssociations, aspectMetadata.childAssociations) &&
                Objects.equals(this.parentPrefixedName, aspectMetadata.parentPrefixedName);
    }

    @Override
    public int hashCode() {
        return Objects.hash(prefixedName, title, description, modelDescriptor, properties, associations, childAssociations, parentPrefixedName);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class AspectMetadata {\n");

        sb.append("    prefixedName: ").append(toIndentedString(prefixedName)).append("\n");
        sb.append("    title: ").append(toIndentedString(title)).append("\n");
        sb.append("    description: ").append(toIndentedString(description)).append("\n");
        sb.append("    modelDescriptor: ").append(toIndentedString(modelDescriptor)).append("\n");
        sb.append("    properties: ").append(toIndentedString(properties)).append("\n");
        sb.append("    associations: ").append(toIndentedString(associations)).append("\n");
        sb.append("    childAssociations: ").append(toIndentedString(childAssociations)).append("\n");
        sb.append("    parentPrefixedName: ").append(toIndentedString(parentPrefixedName)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}