/*-
 * ========================LICENSE_START=================================
 * 
 * Copyright (C) 2025 Regione Piemonte
 * 
 * SPDX-FileCopyrightText: (C) Copyright 2025 Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/*
 * ECMEngine
 * Servizi di fruizione ECM INDEX.
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.csi.scriva.scrivabesrv.business.be.helper.index.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * Rapporto della verifica della firma digitale richiesta con il metodo verifyAsyncDocument
 */
@ApiModel(description = "Rapporto della verifica della firma digitale richiesta con il metodo verifyAsyncDocument")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-03-29T13:41:28.556Z")
@JsonInclude(JsonInclude.Include.NON_NULL)
public class AsyncReport {
    @JsonProperty("status")
    private String status = null;

    @JsonProperty("report")
    private VerifyReport report = null;

    /**
     * Status async report.
     *
     * @param status the status
     * @return the async report
     */
    public AsyncReport status(String status) {
        this.status = status;
        return this;
    }

    /**
     * Stato del report, che può essere READY, SCHEDULED, EXPIRED, ERROR.
     *
     * @return status status
     */
    @ApiModelProperty(example = "SCHEDULED", value = "Stato del report, che può essere READY, SCHEDULED, EXPIRED, ERROR.")
    public String getStatus() {
        return status;
    }

    /**
     * Sets status.
     *
     * @param status the status
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * Report async report.
     *
     * @param report the report
     * @return the async report
     */
    public AsyncReport report(VerifyReport report) {
        this.report = report;
        return this;
    }

    /**
     * Get report
     *
     * @return report report
     */
    @ApiModelProperty(value = "")
    public VerifyReport getReport() {
        return report;
    }

    /**
     * Sets report.
     *
     * @param report the report
     */
    public void setReport(VerifyReport report) {
        this.report = report;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        AsyncReport asyncReport = (AsyncReport) o;
        return Objects.equals(this.status, asyncReport.status) &&
                Objects.equals(this.report, asyncReport.report);
    }

    @Override
    public int hashCode() {
        return Objects.hash(status, report);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class AsyncReport {\n");

        sb.append("    status: ").append(toIndentedString(status)).append("\n");
        sb.append("    report: ").append(toIndentedString(report)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}