/*-
 * ========================LICENSE_START=================================
 * 
 * Copyright (C) 2025 Regione Piemonte
 * 
 * SPDX-FileCopyrightText: (C) Copyright 2025 Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/*
 * ECMEngine
 * Servizi di fruizione ECM INDEX.
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.csi.scriva.scrivabesrv.business.be.helper.index.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * Modello personalizzato dei dati.
 */
@ApiModel(description = "Modello personalizzato dei dati.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-03-29T13:41:28.556Z")
@JsonInclude(JsonInclude.Include.NON_NULL)
public class CustomModel {
    @JsonProperty("prefixedName")
    private String prefixedName = null;

    @JsonProperty("title")
    private String title = null;

    @JsonProperty("description")
    private String description = null;

    @JsonProperty("filename")
    private String filename = null;

    @JsonProperty("active")
    private Boolean active = null;

    /**
     * Prefixed name custom model.
     *
     * @param prefixedName the prefixed name
     * @return the custom model
     */
    public CustomModel prefixedName(String prefixedName) {
        this.prefixedName = prefixedName;
        return this;
    }

    /**
     * Prefixed name dell&#39;elemento.
     *
     * @return prefixedName prefixed name
     */
    @ApiModelProperty(example = "test:model", value = "Prefixed name dell'elemento.")
    public String getPrefixedName() {
        return prefixedName;
    }

    /**
     * Sets prefixed name.
     *
     * @param prefixedName the prefixed name
     */
    public void setPrefixedName(String prefixedName) {
        this.prefixedName = prefixedName;
    }

    /**
     * Title custom model.
     *
     * @param title the title
     * @return the custom model
     */
    public CustomModel title(String title) {
        this.title = title;
        return this;
    }

    /**
     * Titolo dell&#39;elemento.
     *
     * @return title title
     */
    @ApiModelProperty(example = "TEST MODEL", value = "Titolo dell'elemento.")
    public String getTitle() {
        return title;
    }

    /**
     * Sets title.
     *
     * @param title the title
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * Description custom model.
     *
     * @param description the description
     * @return the custom model
     */
    public CustomModel description(String description) {
        this.description = description;
        return this;
    }

    /**
     * Descrizione dell&#39;elemento.
     *
     * @return description description
     */
    @ApiModelProperty(example = "TEST MODEL", value = "Descrizione dell'elemento.")
    public String getDescription() {
        return description;
    }

    /**
     * Sets description.
     *
     * @param description the description
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Filename custom model.
     *
     * @param filename the filename
     * @return the custom model
     */
    public CustomModel filename(String filename) {
        this.filename = filename;
        return this;
    }

    /**
     * Nome del file del modello.
     *
     * @return filename filename
     */
    @ApiModelProperty(example = "test.xml", value = "Nome del file del modello.")
    public String getFilename() {
        return filename;
    }

    /**
     * Sets filename.
     *
     * @param filename the filename
     */
    public void setFilename(String filename) {
        this.filename = filename;
    }

    /**
     * Active custom model.
     *
     * @param active the active
     * @return the custom model
     */
    public CustomModel active(Boolean active) {
        this.active = active;
        return this;
    }

    /**
     * Imposta se il modello à attivo oppure no.
     *
     * @return active boolean
     */
    @ApiModelProperty(value = "Imposta se il modello à attivo oppure no.")
    public Boolean isActive() {
        return active;
    }

    /**
     * Sets active.
     *
     * @param active the active
     */
    public void setActive(Boolean active) {
        this.active = active;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CustomModel customModel = (CustomModel) o;
        return Objects.equals(this.prefixedName, customModel.prefixedName) &&
                Objects.equals(this.title, customModel.title) &&
                Objects.equals(this.description, customModel.description) &&
                Objects.equals(this.filename, customModel.filename) &&
                Objects.equals(this.active, customModel.active);
    }

    @Override
    public int hashCode() {
        return Objects.hash(prefixedName, title, description, filename, active);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class CustomModel {\n");

        sb.append("    prefixedName: ").append(toIndentedString(prefixedName)).append("\n");
        sb.append("    title: ").append(toIndentedString(title)).append("\n");
        sb.append("    description: ").append(toIndentedString(description)).append("\n");
        sb.append("    filename: ").append(toIndentedString(filename)).append("\n");
        sb.append("    active: ").append(toIndentedString(active)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}