/*-
 * ========================LICENSE_START=================================
 * 
 * Copyright (C) 2025 Regione Piemonte
 * 
 * SPDX-FileCopyrightText: (C) Copyright 2025 Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/*
 * ECMEngine
 * Servizi di fruizione ECM INDEX.
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.csi.scriva.scrivabesrv.business.be.helper.index.dto;

/**
 * valori ammessi per action:  * DELETE - Cancella un nodo.  * PURGE - Elimina un nodo cancellato con l&#39;azione delete.  * DELETE_AND_PURGE - Cancella un nodo ed esegue la purge.
 */
public enum DeleteContentAction {

    /**
     * Delete delete content action.
     */
    DELETE("DELETE"),

    /**
     * Purge delete content action.
     */
    PURGE("PURGE"),

    /**
     * Delete and purge delete content action.
     */
    DELETE_AND_PURGE("DELETE_AND_PURGE");

    private String value;

    DeleteContentAction(String value) {
        this.value = value;
    }

    /**
     * Gets value.
     *
     * @return the value
     */
    public String getValue() {
        return value;
    }

    @Override
    public String toString() {
        return String.valueOf(value);
    }

    /**
     * From value delete content action.
     *
     * @param text the text
     * @return the delete content action
     */
    public static DeleteContentAction fromValue(String text) {
        for (DeleteContentAction b : DeleteContentAction.values()) {
            if (String.valueOf(b.value).equals(text)) {
                return b;
            }
        }
        return null;
    }

}