/*-
 * ========================LICENSE_START=================================
 * 
 * Copyright (C) 2025 Regione Piemonte
 * 
 * SPDX-FileCopyrightText: (C) Copyright 2025 Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/*
 * ECMEngine
 * Servizi di fruizione ECM INDEX.
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.csi.scriva.scrivabesrv.business.be.helper.index.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * Informazioni sulla destinazione della copia
 */
@ApiModel(description = "Informazioni sulla destinazione della copia")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-03-29T13:41:28.556Z")
@JsonInclude(JsonInclude.Include.NON_NULL)
public class DestinationInfo {
    @JsonProperty("parentDestinationUid")
    private String parentDestinationUid = null;

    @JsonProperty("operationContext")
    private OperationContext operationContext = null;

    /**
     * Parent destination uid destination info.
     *
     * @param parentDestinationUid the parent destination uid
     * @return the destination info
     */
    public DestinationInfo parentDestinationUid(String parentDestinationUid) {
        this.parentDestinationUid = parentDestinationUid;
        return this;
    }

    /**
     * UID del nodo padre di destinazione della copia.
     *
     * @return parentDestinationUid parent destination uid
     */
    @ApiModelProperty(example = "2bc43299-1ea4-11eb-9204-9f3a5004d33a", value = "UID del nodo padre di destinazione della copia.")
    public String getParentDestinationUid() {
        return parentDestinationUid;
    }

    /**
     * Sets parent destination uid.
     *
     * @param parentDestinationUid the parent destination uid
     */
    public void setParentDestinationUid(String parentDestinationUid) {
        this.parentDestinationUid = parentDestinationUid;
    }

    /**
     * Operation context destination info.
     *
     * @param operationContext the operation context
     * @return the destination info
     */
    public DestinationInfo operationContext(OperationContext operationContext) {
        this.operationContext = operationContext;
        return this;
    }

    /**
     * Get operationContext
     *
     * @return operationContext operation context
     */
    @ApiModelProperty(value = "")
    public OperationContext getOperationContext() {
        return operationContext;
    }

    /**
     * Sets operation context.
     *
     * @param operationContext the operation context
     */
    public void setOperationContext(OperationContext operationContext) {
        this.operationContext = operationContext;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        DestinationInfo destinationInfo = (DestinationInfo) o;
        return Objects.equals(this.parentDestinationUid, destinationInfo.parentDestinationUid) &&
                Objects.equals(this.operationContext, destinationInfo.operationContext);
    }

    @Override
    public int hashCode() {
        return Objects.hash(parentDestinationUid, operationContext);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class DestinationInfo {\n");

        sb.append("    parentDestinationUid: ").append(toIndentedString(parentDestinationUid)).append("\n");
        sb.append("    operationContext: ").append(toIndentedString(operationContext)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}