/*-
 * ========================LICENSE_START=================================
 * 
 * Copyright (C) 2025 Regione Piemonte
 * 
 * SPDX-FileCopyrightText: (C) Copyright 2025 Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/*
 * ECMEngine
 * Servizi di fruizione ECM INDEX.
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.csi.scriva.scrivabesrv.business.be.helper.index.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Elenco di associazioni, utilizzato come valore di ritorno di una ricerca.
 */
@ApiModel(description = "Elenco di associazioni, utilizzato come valore di ritorno di una ricerca.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-03-29T13:41:28.556Z")
@JsonInclude(JsonInclude.Include.NON_NULL)
public class GetAssociationsResponse {
    @JsonProperty("totalResults")
    private Long totalResults = null;

    @JsonProperty("associations")
    private List<Association> associations = null;

    /**
     * Total results get associations response.
     *
     * @param totalResults the total results
     * @return the get associations response
     */
    public GetAssociationsResponse totalResults(Long totalResults) {
        this.totalResults = totalResults;
        return this;
    }

    /**
     * Numero totali di risultati della ricerca.
     *
     * @return totalResults total results
     */
    @ApiModelProperty(example = "1000", value = "Numero totali di risultati della ricerca.")
    public Long getTotalResults() {
        return totalResults;
    }

    /**
     * Sets total results.
     *
     * @param totalResults the total results
     */
    public void setTotalResults(Long totalResults) {
        this.totalResults = totalResults;
    }

    /**
     * Associations get associations response.
     *
     * @param associations the associations
     * @return the get associations response
     */
    public GetAssociationsResponse associations(List<Association> associations) {
        this.associations = associations;
        return this;
    }

    /**
     * Add associations item get associations response.
     *
     * @param associationsItem the associations item
     * @return the get associations response
     */
    public GetAssociationsResponse addAssociationsItem(Association associationsItem) {
        if (this.associations == null) {
            this.associations = new ArrayList<Association>();
        }
        this.associations.add(associationsItem);
        return this;
    }

    /**
     * Elenco di associazioni risultato della ricerca.
     *
     * @return associations associations
     */
    @ApiModelProperty(value = "Elenco di associazioni risultato della ricerca.")
    public List<Association> getAssociations() {
        return associations;
    }

    /**
     * Sets associations.
     *
     * @param associations the associations
     */
    public void setAssociations(List<Association> associations) {
        this.associations = associations;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetAssociationsResponse getAssociationsResponse = (GetAssociationsResponse) o;
        return Objects.equals(this.totalResults, getAssociationsResponse.totalResults) &&
                Objects.equals(this.associations, getAssociationsResponse.associations);
    }

    @Override
    public int hashCode() {
        return Objects.hash(totalResults, associations);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class GetAssociationsResponse {\n");

        sb.append("    totalResults: ").append(toIndentedString(totalResults)).append("\n");
        sb.append("    associations: ").append(toIndentedString(associations)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}