/*-
 * ========================LICENSE_START=================================
 * 
 * Copyright (C) 2025 Regione Piemonte
 * 
 * SPDX-FileCopyrightText: (C) Copyright 2025 Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/*
 * ECMEngine
 * Servizi di fruizione ECM INDEX.
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.csi.scriva.scrivabesrv.business.be.helper.index.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * Rappresenta un job, ovvero una richiesta asincrona di esecuzione di un servizio.
 */
@ApiModel(description = "Rappresenta un job, ovvero una richiesta asincrona di esecuzione di un servizio.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-03-29T13:41:28.556Z")
@JsonInclude(JsonInclude.Include.NON_NULL)
public class Job {
    @JsonProperty("name")
    private String name = null;

    @JsonProperty("status")
    private String status = null;

    @JsonProperty("created")
    private String created = null;

    @JsonProperty("updated")
    private String updated = null;

    @JsonProperty("message")
    private String message = null;

    /**
     * Name job.
     *
     * @param name the name
     * @return the job
     */
    public Job name(String name) {
        this.name = name;
        return this;
    }

    /**
     * Nome del job.
     *
     * @return name name
     */
    @ApiModelProperty(example = "SERVICE_LinkContent_77b51e50-4b4f-11eb-9691-b7b00e8a99a0", value = "Nome del job.")
    public String getName() {
        return name;
    }

    /**
     * Sets name.
     *
     * @param name the name
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Status job.
     *
     * @param status the status
     * @return the job
     */
    public Job status(String status) {
        this.status = status;
        return this;
    }

    /**
     * Stato del job, che può essere READY, RUNNING, FINISHED, ERROR.
     *
     * @return status status
     */
    @ApiModelProperty(example = "FINISHED", value = "Stato del job, che può essere READY, RUNNING, FINISHED, ERROR.")
    public String getStatus() {
        return status;
    }

    /**
     * Sets status.
     *
     * @param status the status
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * Created job.
     *
     * @param created the created
     * @return the job
     */
    public Job created(String created) {
        this.created = created;
        return this;
    }

    /**
     * Data di creazione del job.
     *
     * @return created created
     */
    @ApiModelProperty(example = "2020-12-31T10:03:44.000+0000", value = "Data di creazione del job.")
    public String getCreated() {
        return created;
    }

    /**
     * Sets created.
     *
     * @param created the created
     */
    public void setCreated(String created) {
        this.created = created;
    }

    /**
     * Updated job.
     *
     * @param updated the updated
     * @return the job
     */
    public Job updated(String updated) {
        this.updated = updated;
        return this;
    }

    /**
     * Data di ultimo aggiornamento del job.
     *
     * @return updated updated
     */
    @ApiModelProperty(example = "2020-12-31T10:04:00.000+0000", value = "Data di ultimo aggiornamento del job.")
    public String getUpdated() {
        return updated;
    }

    /**
     * Sets updated.
     *
     * @param updated the updated
     */
    public void setUpdated(String updated) {
        this.updated = updated;
    }

    /**
     * Message job.
     *
     * @param message the message
     * @return the job
     */
    public Job message(String message) {
        this.message = message;
        return this;
    }

    /**
     * Messaggio del job, valorizzato specialmente in caso di errore.
     *
     * @return message message
     */
    @ApiModelProperty(value = "Messaggio del job, valorizzato specialmente in caso di errore.")
    public String getMessage() {
        return message;
    }

    /**
     * Sets message.
     *
     * @param message the message
     */
    public void setMessage(String message) {
        this.message = message;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Job job = (Job) o;
        return Objects.equals(this.name, job.name) &&
                Objects.equals(this.status, job.status) &&
                Objects.equals(this.created, job.created) &&
                Objects.equals(this.updated, job.updated) &&
                Objects.equals(this.message, job.message);
    }

    @Override
    public int hashCode() {
        return Objects.hash(name, status, created, updated, message);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Job {\n");

        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("    status: ").append(toIndentedString(status)).append("\n");
        sb.append("    created: ").append(toIndentedString(created)).append("\n");
        sb.append("    updated: ").append(toIndentedString(updated)).append("\n");
        sb.append("    message: ").append(toIndentedString(message)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}