/*-
 * ========================LICENSE_START=================================
 * 
 * Copyright (C) 2025 Regione Piemonte
 * 
 * SPDX-FileCopyrightText: (C) Copyright 2025 Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/*
 * ECMEngine
 * Servizi di fruizione ECM INDEX.
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.csi.scriva.scrivabesrv.business.be.helper.index.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Versione di un nodo.
 */
@ApiModel(description = "Versione di un nodo.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-03-29T13:41:28.556Z")
@JsonInclude(JsonInclude.Include.NON_NULL)
public class NodeVersion {
    @JsonProperty("creator")
    private String creator = null;

    @JsonProperty("createdDate")
    private String createdDate = null;

    @JsonProperty("description")
    private String description = null;

    @JsonProperty("versionLabel")
    private String versionLabel = null;

    @JsonProperty("versionedNodeUid")
    private String versionedNodeUid = null;

    @JsonProperty("versionProperties")
    private List<Property> versionProperties = null;

    /**
     * Creator node version.
     *
     * @param creator the creator
     * @return the node version
     */
    public NodeVersion creator(String creator) {
        this.creator = creator;
        return this;
    }

    /**
     * Nome utente del creatore della versione.
     *
     * @return creator creator
     */
    @ApiModelProperty(example = "creator", value = "Nome utente del creatore della versione.")
    public String getCreator() {
        return creator;
    }

    /**
     * Sets creator.
     *
     * @param creator the creator
     */
    public void setCreator(String creator) {
        this.creator = creator;
    }

    /**
     * Created date node version.
     *
     * @param createdDate the created date
     * @return the node version
     */
    public NodeVersion createdDate(String createdDate) {
        this.createdDate = createdDate;
        return this;
    }

    /**
     * Data di creazione della versione.
     *
     * @return createdDate created date
     */
    @ApiModelProperty(example = "2020-12-16T09:56:49.059+0000", value = "Data di creazione della versione.")
    public String getCreatedDate() {
        return createdDate;
    }

    /**
     * Sets created date.
     *
     * @param createdDate the created date
     */
    public void setCreatedDate(String createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * Description node version.
     *
     * @param description the description
     * @return the node version
     */
    public NodeVersion description(String description) {
        this.description = description;
        return this;
    }

    /**
     * Descrizione della versione.
     *
     * @return description description
     */
    @ApiModelProperty(example = "description", value = "Descrizione della versione.")
    public String getDescription() {
        return description;
    }

    /**
     * Sets description.
     *
     * @param description the description
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Version label node version.
     *
     * @param versionLabel the version label
     * @return the node version
     */
    public NodeVersion versionLabel(String versionLabel) {
        this.versionLabel = versionLabel;
        return this;
    }

    /**
     * Numero di versione.
     *
     * @return versionLabel version label
     */
    @ApiModelProperty(example = "1", value = "Numero di versione.")
    public String getVersionLabel() {
        return versionLabel;
    }

    /**
     * Sets version label.
     *
     * @param versionLabel the version label
     */
    public void setVersionLabel(String versionLabel) {
        this.versionLabel = versionLabel;
    }

    /**
     * Versioned node uid node version.
     *
     * @param versionedNodeUid the versioned node uid
     * @return the node version
     */
    public NodeVersion versionedNodeUid(String versionedNodeUid) {
        this.versionedNodeUid = versionedNodeUid;
        return this;
    }

    /**
     * UID del nodo da cui la versione è stata creata.
     *
     * @return versionedNodeUid versioned node uid
     */
    @ApiModelProperty(example = "2bc43299-1ea4-11eb-9204-9f3a5004d33a", value = "UID del nodo da cui la versione è stata creata.")
    public String getVersionedNodeUid() {
        return versionedNodeUid;
    }

    /**
     * Sets versioned node uid.
     *
     * @param versionedNodeUid the versioned node uid
     */
    public void setVersionedNodeUid(String versionedNodeUid) {
        this.versionedNodeUid = versionedNodeUid;
    }

    /**
     * Version properties node version.
     *
     * @param versionProperties the version properties
     * @return the node version
     */
    public NodeVersion versionProperties(List<Property> versionProperties) {
        this.versionProperties = versionProperties;
        return this;
    }

    /**
     * Add version properties item node version.
     *
     * @param versionPropertiesItem the version properties item
     * @return the node version
     */
    public NodeVersion addVersionPropertiesItem(Property versionPropertiesItem) {
        if (this.versionProperties == null) {
            this.versionProperties = new ArrayList<Property>();
        }
        this.versionProperties.add(versionPropertiesItem);
        return this;
    }

    /**
     * Proprietà della versione.
     *
     * @return versionProperties version properties
     */
    @ApiModelProperty(value = "Proprietà della versione.")
    public List<Property> getVersionProperties() {
        return versionProperties;
    }

    /**
     * Sets version properties.
     *
     * @param versionProperties the version properties
     */
    public void setVersionProperties(List<Property> versionProperties) {
        this.versionProperties = versionProperties;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        NodeVersion nodeVersion = (NodeVersion) o;
        return Objects.equals(this.creator, nodeVersion.creator) &&
                Objects.equals(this.createdDate, nodeVersion.createdDate) &&
                Objects.equals(this.description, nodeVersion.description) &&
                Objects.equals(this.versionLabel, nodeVersion.versionLabel) &&
                Objects.equals(this.versionedNodeUid, nodeVersion.versionedNodeUid) &&
                Objects.equals(this.versionProperties, nodeVersion.versionProperties);
    }

    @Override
    public int hashCode() {
        return Objects.hash(creator, createdDate, description, versionLabel, versionedNodeUid, versionProperties);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class NodeVersion {\n");

        sb.append("    creator: ").append(toIndentedString(creator)).append("\n");
        sb.append("    createdDate: ").append(toIndentedString(createdDate)).append("\n");
        sb.append("    description: ").append(toIndentedString(description)).append("\n");
        sb.append("    versionLabel: ").append(toIndentedString(versionLabel)).append("\n");
        sb.append("    versionedNodeUid: ").append(toIndentedString(versionedNodeUid)).append("\n");
        sb.append("    versionProperties: ").append(toIndentedString(versionProperties)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}