/*-
 * ========================LICENSE_START=================================
 * 
 * Copyright (C) 2025 Regione Piemonte
 * 
 * SPDX-FileCopyrightText: (C) Copyright 2025 Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/*
 * ECMEngine
 * Servizi di fruizione ECM INDEX.
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.csi.scriva.scrivabesrv.business.be.helper.index.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * Path del nodo.
 */
@ApiModel(description = "Path del nodo.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-03-29T13:41:28.556Z")
@JsonInclude(JsonInclude.Include.NON_NULL)
public class PathInfo {
    @JsonProperty("path")
    private String path = null;

    @JsonProperty("primary")
    private Boolean primary = null;

    /**
     * Path path info.
     *
     * @param path the path
     * @return the path info
     */
    public PathInfo path(String path) {
        this.path = path;
        return this;
    }

    /**
     * Rappresenta un percorso
     *
     * @return path path
     */
    @ApiModelProperty(example = "/app:company_home/cm:prova", value = "Rappresenta un percorso")
    public String getPath() {
        return path;
    }

    /**
     * Sets path.
     *
     * @param path the path
     */
    public void setPath(String path) {
        this.path = path;
    }

    /**
     * Primary path info.
     *
     * @param primary the primary
     * @return the path info
     */
    public PathInfo primary(Boolean primary) {
        this.primary = primary;
        return this;
    }

    /**
     * Valore del flag che caratterizza il path come \&quot;primario\&quot;.
     *
     * @return primary boolean
     */
    @ApiModelProperty(value = "Valore del flag che caratterizza il path come \"primario\".")
    public Boolean isPrimary() {
        return primary;
    }

    /**
     * Sets primary.
     *
     * @param primary the primary
     */
    public void setPrimary(Boolean primary) {
        this.primary = primary;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        PathInfo pathInfo = (PathInfo) o;
        return Objects.equals(this.path, pathInfo.path) &&
                Objects.equals(this.primary, pathInfo.primary);
    }

    @Override
    public int hashCode() {
        return Objects.hash(path, primary);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class PathInfo {\n");

        sb.append("    path: ").append(toIndentedString(path)).append("\n");
        sb.append("    primary: ").append(toIndentedString(primary)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}