/*-
 * ========================LICENSE_START=================================
 * 
 * Copyright (C) 2025 Regione Piemonte
 * 
 * SPDX-FileCopyrightText: (C) Copyright 2025 Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/*
 * ECMEngine
 * Servizi di fruizione ECM INDEX.
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.csi.scriva.scrivabesrv.business.be.helper.index.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * Informazioni per la creazione di un link di condivisione di un documento.
 */
@ApiModel(description = "Informazioni per la creazione di un link di condivisione di un documento.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-03-29T13:41:28.556Z")
@JsonInclude(JsonInclude.Include.NON_NULL)
public class SharingInfo {
    @JsonProperty("sharedLink")
    private String sharedLink = null;

    @JsonProperty("contentPropertyPrefixedName")
    private String contentPropertyPrefixedName = null;

    @JsonProperty("source")
    private String source = null;

    @JsonProperty("fromDate")
    private String fromDate = null;

    @JsonProperty("toDate")
    private String toDate = null;

    @JsonProperty("resultContentDisposition")
    private String resultContentDisposition = null;

    @JsonProperty("resultPropertyPrefixedName")
    private String resultPropertyPrefixedName = null;

    /**
     * Shared link sharing info.
     *
     * @param sharedLink the shared link
     * @return the sharing info
     */
    public SharingInfo sharedLink(String sharedLink) {
        this.sharedLink = sharedLink;
        return this;
    }

    /**
     * Url della condivisione.
     *
     * @return sharedLink shared link
     */
    @ApiModelProperty(example = "http://tst-jboss-01.csi.it:22310/ecmenginecxf-test/http/download/cHJpbWFyeXx0ZW1wfDhlOTcyMTNkNmM3MzExZWJiOGUyYzkwY2M3ZTBhMDZkfDE2MTMwNTI5MTQ2NTJ8MjY1NTY3Mw", value = "Url della condivisione.")
    public String getSharedLink() {
        return sharedLink;
    }

    /**
     * Sets shared link.
     *
     * @param sharedLink the shared link
     */
    public void setSharedLink(String sharedLink) {
        this.sharedLink = sharedLink;
    }

    /**
     * Content property prefixed name sharing info.
     *
     * @param contentPropertyPrefixedName the content property prefixed name
     * @return the sharing info
     */
    public SharingInfo contentPropertyPrefixedName(String contentPropertyPrefixedName) {
        this.contentPropertyPrefixedName = contentPropertyPrefixedName;
        return this;
    }

    /**
     * Prefixed name della proprietà che rappresenta il contenuto binario del nodo.
     *
     * @return contentPropertyPrefixedName content property prefixed name
     */
    @ApiModelProperty(example = "cm:content", value = "Prefixed name della proprietà che rappresenta il contenuto binario del nodo.")
    public String getContentPropertyPrefixedName() {
        return contentPropertyPrefixedName;
    }

    /**
     * Sets content property prefixed name.
     *
     * @param contentPropertyPrefixedName the content property prefixed name
     */
    public void setContentPropertyPrefixedName(String contentPropertyPrefixedName) {
        this.contentPropertyPrefixedName = contentPropertyPrefixedName;
    }

    /**
     * Source sharing info.
     *
     * @param source the source
     * @return the sharing info
     */
    public SharingInfo source(String source) {
        this.source = source;
        return this;
    }

    /**
     * Origine del link Valori :    &gt;      intranet1 esposizione interna (http)      intranet2 esposizione interna (https)      internet eposizione INTERNET (https).
     *
     * @return source source
     */
    @ApiModelProperty(example = "intranet", value = "Origine del link Valori :    >      intranet1 esposizione interna (http)      intranet2 esposizione interna (https)      internet eposizione INTERNET (https). ")
    public String getSource() {
        return source;
    }

    /**
     * Sets source.
     *
     * @param source the source
     */
    public void setSource(String source) {
        this.source = source;
    }

    /**
     * From date sharing info.
     *
     * @param fromDate the from date
     * @return the sharing info
     */
    public SharingInfo fromDate(String fromDate) {
        this.fromDate = fromDate;
        return this;
    }

    /**
     * Data di inizio validità del link.
     *
     * @return fromDate from date
     */
    @ApiModelProperty(example = "2020-12-16T13:59:56.986+01:00", value = "Data di inizio validità del link.")
    public String getFromDate() {
        return fromDate;
    }

    /**
     * Sets from date.
     *
     * @param fromDate the from date
     */
    public void setFromDate(String fromDate) {
        this.fromDate = fromDate;
    }

    /**
     * To date sharing info.
     *
     * @param toDate the to date
     * @return the sharing info
     */
    public SharingInfo toDate(String toDate) {
        this.toDate = toDate;
        return this;
    }

    /**
     * Data di termine validita&#39; del link.
     *
     * @return toDate to date
     */
    @ApiModelProperty(example = "2020-12-16T13:59:56.986+01:00", value = "Data di termine validita' del link.")
    public String getToDate() {
        return toDate;
    }

    /**
     * Sets to date.
     *
     * @param toDate the to date
     */
    public void setToDate(String toDate) {
        this.toDate = toDate;
    }

    /**
     * Result content disposition sharing info.
     *
     * @param resultContentDisposition the result content disposition
     * @return the sharing info
     */
    public SharingInfo resultContentDisposition(String resultContentDisposition) {
        this.resultContentDisposition = resultContentDisposition;
        return this;
    }

    /**
     * Specifica il Content-Disposition in uscita (per uso client).
     *
     * @return resultContentDisposition result content disposition
     */
    @ApiModelProperty(value = "Specifica il Content-Disposition in uscita (per uso client).")
    public String getResultContentDisposition() {
        return resultContentDisposition;
    }

    /**
     * Sets result content disposition.
     *
     * @param resultContentDisposition the result content disposition
     */
    public void setResultContentDisposition(String resultContentDisposition) {
        this.resultContentDisposition = resultContentDisposition;
    }

    /**
     * Result property prefixed name sharing info.
     *
     * @param resultPropertyPrefixedName the result property prefixed name
     * @return the sharing info
     */
    public SharingInfo resultPropertyPrefixedName(String resultPropertyPrefixedName) {
        this.resultPropertyPrefixedName = resultPropertyPrefixedName;
        return this;
    }

    /**
     * Prefixed name della proprietà che contenente il nome del file.
     *
     * @return resultPropertyPrefixedName result property prefixed name
     */
    @ApiModelProperty(value = "Prefixed name della proprietà che contenente il nome del file.")
    public String getResultPropertyPrefixedName() {
        return resultPropertyPrefixedName;
    }

    /**
     * Sets result property prefixed name.
     *
     * @param resultPropertyPrefixedName the result property prefixed name
     */
    public void setResultPropertyPrefixedName(String resultPropertyPrefixedName) {
        this.resultPropertyPrefixedName = resultPropertyPrefixedName;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        SharingInfo sharingInfo = (SharingInfo) o;
        return Objects.equals(this.sharedLink, sharingInfo.sharedLink) &&
                Objects.equals(this.contentPropertyPrefixedName, sharingInfo.contentPropertyPrefixedName) &&
                Objects.equals(this.source, sharingInfo.source) &&
                Objects.equals(this.fromDate, sharingInfo.fromDate) &&
                Objects.equals(this.toDate, sharingInfo.toDate) &&
                Objects.equals(this.resultContentDisposition, sharingInfo.resultContentDisposition) &&
                Objects.equals(this.resultPropertyPrefixedName, sharingInfo.resultPropertyPrefixedName);
    }

    @Override
    public int hashCode() {
        return Objects.hash(sharedLink, contentPropertyPrefixedName, source, fromDate, toDate, resultContentDisposition, resultPropertyPrefixedName);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class SharingInfo {\n");

        sb.append("    sharedLink: ").append(toIndentedString(sharedLink)).append("\n");
        sb.append("    contentPropertyPrefixedName: ").append(toIndentedString(contentPropertyPrefixedName)).append("\n");
        sb.append("    source: ").append(toIndentedString(source)).append("\n");
        sb.append("    fromDate: ").append(toIndentedString(fromDate)).append("\n");
        sb.append("    toDate: ").append(toIndentedString(toDate)).append("\n");
        sb.append("    resultContentDisposition: ").append(toIndentedString(resultContentDisposition)).append("\n");
        sb.append("    resultPropertyPrefixedName: ").append(toIndentedString(resultPropertyPrefixedName)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}