/*-
 * ========================LICENSE_START=================================
 * 
 * Copyright (C) 2025 Regione Piemonte
 * 
 * SPDX-FileCopyrightText: (C) Copyright 2025 Regione Piemonte
 * SPDX-License-Identifier: EUPL-1.2
 * =========================LICENSE_END==================================
 */
/*
 * ECMEngine
 * Servizi di fruizione ECM INDEX.
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.csi.scriva.scrivabesrv.business.be.helper.index.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * Parametri di verifica.
 */
@ApiModel(description = "Parametri di verifica.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-03-29T13:41:28.556Z")
@JsonInclude(JsonInclude.Include.NON_NULL)
public class VerifyParameter {
    @JsonProperty("verificationDate")
    private String verificationDate = null;

    @JsonProperty("verificationType")
    private Integer verificationType = null;

    @JsonProperty("profileType")
    private Integer profileType = null;

    @JsonProperty("verificationScope")
    private Integer verificationScope = null;

    /**
     * Verification date verify parameter.
     *
     * @param verificationDate the verification date
     * @return the verify parameter
     */
    public VerifyParameter verificationDate(String verificationDate) {
        this.verificationDate = verificationDate;
        return this;
    }

    /**
     * Data di verifica.
     *
     * @return verificationDate verification date
     */
    @ApiModelProperty(example = "", value = "Data di verifica.")
    public String getVerificationDate() {
        return verificationDate;
    }

    /**
     * Sets verification date.
     *
     * @param verificationDate the verification date
     */
    public void setVerificationDate(String verificationDate) {
        this.verificationDate = verificationDate;
    }

    /**
     * Verification type verify parameter.
     *
     * @param verificationType the verification type
     * @return the verify parameter
     */
    public VerifyParameter verificationType(Integer verificationType) {
        this.verificationType = verificationType;
        return this;
    }

    /**
     * Tipo di verifica.
     *
     * @return verificationType verification type
     */
    @ApiModelProperty(example = "1", value = "Tipo di verifica.")
    public Integer getVerificationType() {
        return verificationType;
    }

    /**
     * Sets verification type.
     *
     * @param verificationType the verification type
     */
    public void setVerificationType(Integer verificationType) {
        this.verificationType = verificationType;
    }

    /**
     * Profile type verify parameter.
     *
     * @param profileType the profile type
     * @return the verify parameter
     */
    public VerifyParameter profileType(Integer profileType) {
        this.profileType = profileType;
        return this;
    }

    /**
     * Tipo di profilo.
     *
     * @return profileType profile type
     */
    @ApiModelProperty(example = "1", value = "Tipo di profilo.")
    public Integer getProfileType() {
        return profileType;
    }

    /**
     * Sets profile type.
     *
     * @param profileType the profile type
     */
    public void setProfileType(Integer profileType) {
        this.profileType = profileType;
    }

    /**
     * Verification scope verify parameter.
     *
     * @param verificationScope the verification scope
     * @return the verify parameter
     */
    public VerifyParameter verificationScope(Integer verificationScope) {
        this.verificationScope = verificationScope;
        return this;
    }

    /**
     * Tipo di certificato.
     *
     * @return verificationScope verification scope
     */
    @ApiModelProperty(example = "1", value = "Tipo di certificato.")
    public Integer getVerificationScope() {
        return verificationScope;
    }

    /**
     * Sets verification scope.
     *
     * @param verificationScope the verification scope
     */
    public void setVerificationScope(Integer verificationScope) {
        this.verificationScope = verificationScope;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        VerifyParameter verifyParameter = (VerifyParameter) o;
        return Objects.equals(this.verificationDate, verifyParameter.verificationDate) &&
                Objects.equals(this.verificationType, verifyParameter.verificationType) &&
                Objects.equals(this.profileType, verifyParameter.profileType) &&
                Objects.equals(this.verificationScope, verifyParameter.verificationScope);
    }

    @Override
    public int hashCode() {
        return Objects.hash(verificationDate, verificationType, profileType, verificationScope);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class VerifyParameter {\n");

        sb.append("    verificationDate: ").append(toIndentedString(verificationDate)).append("\n");
        sb.append("    verificationType: ").append(toIndentedString(verificationType)).append("\n");
        sb.append("    profileType: ").append(toIndentedString(profileType)).append("\n");
        sb.append("    verificationScope: ").append(toIndentedString(verificationScope)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}