/* *****************************************************
 * Copyright Regione Piemonte - 2025
 * SPDX-License-Identifier: EUPL-1.2-or-later
 ******************************************************/

-- Views
DROP VIEW IF EXISTS v_utility_lista_istanze;


-- Functions
DROP FUNCTION IF EXISTS fnc_delete_istanza(p_idistanza integer))               CASCADE;


-- Tables
DROP TABLE IF EXISTS scriva_d_ambito                       CASCADE;
DROP TABLE IF EXISTS scriva_d_categoria_allegato           CASCADE;
DROP TABLE IF EXISTS scriva_d_categoria_oggetto            CASCADE;
DROP TABLE IF EXISTS scriva_d_classe_allegato              CASCADE;
DROP TABLE IF EXISTS scriva_d_componente_app               CASCADE;
DROP TABLE IF EXISTS scriva_d_config_geeco                 CASCADE;
DROP TABLE IF EXISTS scriva_d_configurazione               CASCADE;
DROP TABLE IF EXISTS scriva_d_continente                   CASCADE;
DROP TABLE IF EXISTS scriva_d_dizionario_placeholder       CASCADE;
DROP TABLE IF EXISTS scriva_d_ente_creditore               CASCADE;
DROP TABLE IF EXISTS scriva_d_esito_procedimento           CASCADE;
DROP TABLE IF EXISTS scriva_d_funzionalita                 CASCADE;
DROP TABLE IF EXISTS scriva_d_gestione_attore              CASCADE;
DROP TABLE IF EXISTS scriva_d_gruppo_pagamento             CASCADE;
DROP TABLE IF EXISTS scriva_d_informazioni_scriva          CASCADE;
DROP TABLE IF EXISTS scriva_d_livello_help                 CASCADE;
DROP TABLE IF EXISTS scriva_d_mappa_fonte_esterna          CASCADE;
DROP TABLE IF EXISTS scriva_d_masterdata                   CASCADE;
DROP TABLE IF EXISTS scriva_d_natura_oggetto               CASCADE;
DROP TABLE IF EXISTS scriva_d_origine_limiti               CASCADE;
DROP TABLE IF EXISTS scriva_d_ruolo_compilante             CASCADE;
DROP TABLE IF EXISTS scriva_d_ruolo_soggetto               CASCADE;
DROP TABLE IF EXISTS scriva_d_stato_elabora                CASCADE;
DROP TABLE IF EXISTS scriva_d_stato_istanza                CASCADE;
DROP TABLE IF EXISTS scriva_d_stato_notifica               CASCADE;
DROP TABLE IF EXISTS scriva_d_stato_oggetto                CASCADE;
DROP TABLE IF EXISTS scriva_d_stato_osservazione           CASCADE;
DROP TABLE IF EXISTS scriva_d_stato_pagamento              CASCADE;
DROP TABLE IF EXISTS scriva_d_stato_proced_statale         CASCADE;
DROP TABLE IF EXISTS scriva_d_stato_tentativo_pag          CASCADE;
DROP TABLE IF EXISTS scriva_d_template_comunica            CASCADE;
DROP TABLE IF EXISTS scriva_d_tipo_area_protetta           CASCADE;
DROP TABLE IF EXISTS scriva_d_tipo_competenza              CASCADE;
DROP TABLE IF EXISTS scriva_d_tipo_destinatario            CASCADE;
DROP TABLE IF EXISTS scriva_d_tipo_help                    CASCADE;
DROP TABLE IF EXISTS scriva_d_tipo_integrazione            CASCADE;
DROP TABLE IF EXISTS scriva_d_tipo_messaggio               CASCADE;
DROP TABLE IF EXISTS scriva_d_tipo_natura_2000             CASCADE;
DROP TABLE IF EXISTS scriva_d_tipo_natura_giuridica        CASCADE;
DROP TABLE IF EXISTS scriva_d_tipo_notifica                CASCADE;
DROP TABLE IF EXISTS scriva_d_tipo_oggetto_app             CASCADE;
DROP TABLE IF EXISTS scriva_d_tipo_quadro                  CASCADE;
DROP TABLE IF EXISTS scriva_d_tipo_responsabile            CASCADE;
DROP TABLE IF EXISTS scriva_d_tipo_soggetto                CASCADE;
DROP TABLE IF EXISTS scriva_d_tipo_vincolo_aut             CASCADE;
DROP TABLE IF EXISTS scriva_s_catasto_ubi_ogg_ist          CASCADE;
DROP TABLE IF EXISTS scriva_s_funzionario                  CASCADE;
DROP TABLE IF EXISTS scriva_s_gruppo_soggetto              CASCADE;
DROP TABLE IF EXISTS scriva_s_istanza_competenza           CASCADE;
DROP TABLE IF EXISTS scriva_s_istanza_vincolo_aut          CASCADE;
DROP TABLE IF EXISTS scriva_s_ogg_area_protetta            CASCADE;
DROP TABLE IF EXISTS scriva_s_ogg_istanza_categoria        CASCADE;
DROP TABLE IF EXISTS scriva_s_ogg_natura_2000              CASCADE;
DROP TABLE IF EXISTS scriva_s_ogg_vincolo_autorizza        CASCADE;
DROP TABLE IF EXISTS scriva_s_oggetto                      CASCADE;
DROP TABLE IF EXISTS scriva_s_oggetto_ist_figlio           CASCADE;
DROP TABLE IF EXISTS scriva_s_oggetto_istanza              CASCADE;
DROP TABLE IF EXISTS scriva_s_recapito_alternativo         CASCADE;
DROP TABLE IF EXISTS scriva_s_soggetto                     CASCADE;
DROP TABLE IF EXISTS scriva_s_soggetto_gruppo              CASCADE;
DROP TABLE IF EXISTS scriva_s_soggetto_istanza             CASCADE;
DROP TABLE IF EXISTS scriva_s_ubica_oggetto                CASCADE;
DROP TABLE IF EXISTS scriva_s_ubica_oggetto_istanza        CASCADE;
DROP TABLE IF EXISTS scriva_t_compilante                   CASCADE;
DROP TABLE IF EXISTS scriva_t_funzionario                  CASCADE;
DROP TABLE IF EXISTS scriva_w_acq_soggetto                 CASCADE;
DROP TABLE IF EXISTS scriva_w_del_istanza                  CASCADE;
DROP TABLE IF EXISTS scriva_d_canale_notifica              CASCADE;
DROP TABLE IF EXISTS scriva_d_config_json_data             CASCADE;
DROP TABLE IF EXISTS scriva_d_help                         CASCADE;
DROP TABLE IF EXISTS scriva_d_messaggio                    CASCADE;
DROP TABLE IF EXISTS scriva_d_nazione                      CASCADE;
DROP TABLE IF EXISTS scriva_d_profilo_app                  CASCADE;
DROP TABLE IF EXISTS scriva_d_quadro                       CASCADE;
DROP TABLE IF EXISTS scriva_d_regione                      CASCADE;
DROP TABLE IF EXISTS scriva_d_tipo_abilitazione            CASCADE;
DROP TABLE IF EXISTS scriva_d_tipo_adempimento             CASCADE;
DROP TABLE IF EXISTS scriva_d_tipo_elabora                 CASCADE;
DROP TABLE IF EXISTS scriva_d_tipo_evento                  CASCADE;
DROP TABLE IF EXISTS scriva_d_tipo_pagamento               CASCADE;
DROP TABLE IF EXISTS scriva_d_tipologia_allegato           CASCADE;
DROP TABLE IF EXISTS scriva_d_tipologia_oggetto            CASCADE;
DROP TABLE IF EXISTS scriva_d_vincolo_autorizza            CASCADE;
DROP TABLE IF EXISTS scriva_r_categoria_tipo_ogg           CASCADE;
DROP TABLE IF EXISTS scriva_r_compilante_preferenza        CASCADE;
DROP TABLE IF EXISTS scriva_r_compilante_preferenza_cn     CASCADE;
DROP TABLE IF EXISTS scriva_r_funzionario_profilo          CASCADE;
DROP TABLE IF EXISTS scriva_r_geeco_layer_virtuali         CASCADE;
DROP TABLE IF EXISTS scriva_r_richiesta_accredito          CASCADE;
DROP TABLE IF EXISTS scriva_r_tipo_adempi_profilo          CASCADE;
DROP TABLE IF EXISTS scriva_r_tipo_competenza_cat          CASCADE;
DROP TABLE IF EXISTS scriva_r_tipo_notifica_evento         CASCADE;
DROP TABLE IF EXISTS scriva_s_nazione                      CASCADE;
DROP TABLE IF EXISTS scriva_s_regione                      CASCADE;
DROP TABLE IF EXISTS scriva_t_elabora                      CASCADE;
DROP TABLE IF EXISTS scriva_t_tentativo_pagamento          CASCADE;
DROP TABLE IF EXISTS scriva_d_adempimento                  CASCADE;
DROP TABLE IF EXISTS scriva_d_destinatario                 CASCADE;
DROP TABLE IF EXISTS scriva_d_oggetto_app                  CASCADE;
DROP TABLE IF EXISTS scriva_d_provincia                    CASCADE;
DROP TABLE IF EXISTS scriva_d_template                     CASCADE;
DROP TABLE IF EXISTS scriva_log_acq_allegato               CASCADE;
DROP TABLE IF EXISTS scriva_log_acq_istanza                CASCADE;
DROP TABLE IF EXISTS scriva_log_acq_soggetto               CASCADE;
DROP TABLE IF EXISTS scriva_r_adempi_categoria_ogg         CASCADE;
DROP TABLE IF EXISTS scriva_r_adempi_config                CASCADE;
DROP TABLE IF EXISTS scriva_r_adempi_esito_proced          CASCADE;
DROP TABLE IF EXISTS scriva_r_adempi_est_allegato          CASCADE;
DROP TABLE IF EXISTS scriva_r_adempi_provincia             CASCADE;
DROP TABLE IF EXISTS scriva_r_adempi_ruolo_app             CASCADE;
DROP TABLE IF EXISTS scriva_r_adempi_ruolo_compila         CASCADE;
DROP TABLE IF EXISTS scriva_r_adempi_ruolo_sogg            CASCADE;
DROP TABLE IF EXISTS scriva_r_adempi_tipo_allegato         CASCADE;
DROP TABLE IF EXISTS scriva_r_adempi_tipo_oggetto          CASCADE;
DROP TABLE IF EXISTS scriva_r_adempi_vincolo_aut           CASCADE;
DROP TABLE IF EXISTS scriva_r_configura_ruolo_sogg         CASCADE;
DROP TABLE IF EXISTS scriva_r_destinatario_canale          CASCADE;
DROP TABLE IF EXISTS scriva_r_geeco_layer_mappa            CASCADE;
DROP TABLE IF EXISTS scriva_r_profilo_ogg_app              CASCADE;
DROP TABLE IF EXISTS scriva_r_registro_elabora             CASCADE;
DROP TABLE IF EXISTS scriva_r_stato_istanza_adempi         CASCADE;
DROP TABLE IF EXISTS scriva_r_template_quadro              CASCADE;
DROP TABLE IF EXISTS scriva_r_tipo_adempi_ogg_app          CASCADE;
DROP TABLE IF EXISTS scriva_r_tipo_notifica_evento_adempi  CASCADE;
DROP TABLE IF EXISTS scriva_r_vincolo_tipo_allegato        CASCADE;
DROP TABLE IF EXISTS scriva_s_provincia                    CASCADE;
DROP TABLE IF EXISTS scriva_d_comune                       CASCADE;
DROP TABLE IF EXISTS scriva_s_comune                       CASCADE;
DROP TABLE IF EXISTS scriva_t_competenza_territorio        CASCADE;
DROP TABLE IF EXISTS scriva_t_soggetto                     CASCADE;
DROP TABLE IF EXISTS scriva_d_adempi_tipo_pagamento        CASCADE;
DROP TABLE IF EXISTS scriva_r_adempi_competenza            CASCADE;
DROP TABLE IF EXISTS scriva_r_competenza_comune            CASCADE;
DROP TABLE IF EXISTS scriva_r_competenza_provincia         CASCADE;
DROP TABLE IF EXISTS scriva_r_competenza_regione           CASCADE;
DROP TABLE IF EXISTS scriva_r_competenza_responsabile      CASCADE;
DROP TABLE IF EXISTS scriva_r_funzionario_compete          CASCADE;
DROP TABLE IF EXISTS scriva_r_notifica_configurazione      CASCADE;
DROP TABLE IF EXISTS scriva_r_riscossione_ente             CASCADE;
DROP TABLE IF EXISTS scriva_r_notifica_config_allegato     CASCADE;
DROP TABLE IF EXISTS scriva_r_risco_stato_istanza          CASCADE;
DROP TABLE IF EXISTS scriva_geo_area_ogg_istanza           CASCADE;
DROP TABLE IF EXISTS scriva_geo_linea_ogg_istanza          CASCADE;
DROP TABLE IF EXISTS scriva_geo_punto_ogg_istanza          CASCADE;
DROP TABLE IF EXISTS scriva_r_catasto_ubi_ogg_ist          CASCADE;
DROP TABLE IF EXISTS scriva_r_integra_istanza_allegato     CASCADE;
DROP TABLE IF EXISTS scriva_r_istanza_attore               CASCADE;
DROP TABLE IF EXISTS scriva_r_istanza_competenza           CASCADE;
DROP TABLE IF EXISTS scriva_r_istanza_competenza_oggetto   CASCADE;
DROP TABLE IF EXISTS scriva_r_istanza_evento               CASCADE;
DROP TABLE IF EXISTS scriva_r_istanza_osservazione         CASCADE;
DROP TABLE IF EXISTS scriva_r_istanza_responsabile         CASCADE;
DROP TABLE IF EXISTS scriva_r_istanza_stato                CASCADE;
DROP TABLE IF EXISTS scriva_r_istanza_storico              CASCADE;
DROP TABLE IF EXISTS scriva_r_istanza_vincolo_aut          CASCADE;
DROP TABLE IF EXISTS scriva_r_nota_istanza                 CASCADE;
DROP TABLE IF EXISTS scriva_r_notifica_allegato            CASCADE;
DROP TABLE IF EXISTS scriva_r_notifica_applicativa         CASCADE;
DROP TABLE IF EXISTS scriva_r_ogg_area_protetta            CASCADE;
DROP TABLE IF EXISTS scriva_r_ogg_istanza_categoria        CASCADE;
DROP TABLE IF EXISTS scriva_r_ogg_natura_2000              CASCADE;
DROP TABLE IF EXISTS scriva_r_ogg_vincolo_autorizza        CASCADE;
DROP TABLE IF EXISTS scriva_r_oggetto_ist_figlio           CASCADE;
DROP TABLE IF EXISTS scriva_r_pagamento_istanza            CASCADE;
DROP TABLE IF EXISTS scriva_r_recapito_alternativo         CASCADE;
DROP TABLE IF EXISTS scriva_r_referente_istanza            CASCADE;
DROP TABLE IF EXISTS scriva_r_soggetto_gruppo              CASCADE;
DROP TABLE IF EXISTS scriva_r_tentativo_dettaglio          CASCADE;
DROP TABLE IF EXISTS scriva_r_ubica_oggetto                CASCADE;
DROP TABLE IF EXISTS scriva_r_ubica_oggetto_istanza        CASCADE;
DROP TABLE IF EXISTS scriva_t_allegato_istanza             CASCADE;
DROP TABLE IF EXISTS scriva_t_gruppo_soggetto              CASCADE;
DROP TABLE IF EXISTS scriva_t_integrazione_istanza         CASCADE;
DROP TABLE IF EXISTS scriva_t_istanza                      CASCADE;
DROP TABLE IF EXISTS scriva_t_notifica                     CASCADE;
DROP TABLE IF EXISTS scriva_t_oggetto                      CASCADE;
DROP TABLE IF EXISTS scriva_t_oggetto_istanza              CASCADE;
DROP TABLE IF EXISTS scriva_t_soggetto_istanza             CASCADE;



-- Sequuences
DROP SEQUENCE IF EXISTS seq_scriva_cod_allegato;
DROP SEQUENCE IF EXISTS seq_scriva_cod_gruppo_soggetto;
DROP SEQUENCE IF EXISTS seq_scriva_cod_istanza;
DROP SEQUENCE IF EXISTS seq_scriva_cod_recapito_alternativo;
DROP SEQUENCE IF EXISTS seq_scriva_cod_scriva;
DROP SEQUENCE IF EXISTS seq_scriva_geo_area_ogg_istanza;
DROP SEQUENCE IF EXISTS seq_scriva_geo_id_geometrico;
DROP SEQUENCE IF EXISTS seq_scriva_geo_linea_ogg_istanza;
DROP SEQUENCE IF EXISTS seq_scriva_geo_punto_ogg_istanza;
DROP SEQUENCE IF EXISTS seq_scriva_log_acq_allegato;
DROP SEQUENCE IF EXISTS seq_scriva_log_acq_istanza;
DROP SEQUENCE IF EXISTS seq_scriva_log_acq_soggetto;
DROP SEQUENCE IF EXISTS seq_scriva_r_catasto_ubi_ogg_ist;
DROP SEQUENCE IF EXISTS seq_scriva_r_competenza_responsabile;
DROP SEQUENCE IF EXISTS seq_scriva_r_compilante_preferenza;
DROP SEQUENCE IF EXISTS seq_scriva_r_compilante_preferenza_cn;
DROP SEQUENCE IF EXISTS seq_scriva_r_integra_istanza_allegato;
DROP SEQUENCE IF EXISTS seq_scriva_r_istanza_attore;
DROP SEQUENCE IF EXISTS seq_scriva_r_istanza_evento;
DROP SEQUENCE IF EXISTS seq_scriva_r_istanza_osservazione;
DROP SEQUENCE IF EXISTS seq_scriva_r_istanza_responsabile;
DROP SEQUENCE IF EXISTS seq_scriva_r_istanza_storico;
DROP SEQUENCE IF EXISTS seq_scriva_r_istanza_vincolo_aut;
DROP SEQUENCE IF EXISTS seq_scriva_r_nota_istanza;
DROP SEQUENCE IF EXISTS seq_scriva_r_notifica_allegato;
DROP SEQUENCE IF EXISTS seq_scriva_r_notifica_applicativa;
DROP SEQUENCE IF EXISTS seq_scriva_r_ogg_area_protetta;
DROP SEQUENCE IF EXISTS seq_scriva_r_ogg_natura_2000;
DROP SEQUENCE IF EXISTS seq_scriva_r_ogg_vincolo_autorizza;
DROP SEQUENCE IF EXISTS seq_scriva_r_pagamento_istanza;
DROP SEQUENCE IF EXISTS seq_scriva_r_recapito_alternativo;
DROP SEQUENCE IF EXISTS seq_scriva_r_referente_istanza;
DROP SEQUENCE IF EXISTS seq_scriva_r_registro_elabora;
DROP SEQUENCE IF EXISTS seq_scriva_r_richiesta_accredito;
DROP SEQUENCE IF EXISTS seq_scriva_r_ubica_oggetto;
DROP SEQUENCE IF EXISTS seq_scriva_r_ubica_oggetto_istanza;
DROP SEQUENCE IF EXISTS seq_scriva_s_catasto_ubi_ogg_ist;
DROP SEQUENCE IF EXISTS seq_scriva_s_gruppo_soggetto;
DROP SEQUENCE IF EXISTS seq_scriva_s_istanza_competenza;
DROP SEQUENCE IF EXISTS seq_scriva_s_istanza_vincolo_aut;
DROP SEQUENCE IF EXISTS seq_scriva_s_ogg_area_protetta;
DROP SEQUENCE IF EXISTS seq_scriva_s_ogg_istanza_categoria;
DROP SEQUENCE IF EXISTS seq_scriva_s_ogg_natura_2000;
DROP SEQUENCE IF EXISTS seq_scriva_s_ogg_vincolo_autorizza;
DROP SEQUENCE IF EXISTS seq_scriva_s_oggetto;
DROP SEQUENCE IF EXISTS seq_scriva_s_oggetto_ist_figlio;
DROP SEQUENCE IF EXISTS seq_scriva_s_oggetto_istanza;
DROP SEQUENCE IF EXISTS seq_scriva_s_recapito_alternativo;
DROP SEQUENCE IF EXISTS seq_scriva_s_soggetto;
DROP SEQUENCE IF EXISTS seq_scriva_s_soggetto_gruppo;
DROP SEQUENCE IF EXISTS seq_scriva_s_soggetto_istanza;
DROP SEQUENCE IF EXISTS seq_scriva_s_ubica_oggetto;
DROP SEQUENCE IF EXISTS seq_scriva_s_ubica_oggetto_istanza;
DROP SEQUENCE IF EXISTS seq_scriva_t_allegato_istanza;
DROP SEQUENCE IF EXISTS seq_scriva_t_compilante;
DROP SEQUENCE IF EXISTS seq_scriva_t_elabora;
DROP SEQUENCE IF EXISTS seq_scriva_t_gruppo_soggetto;
DROP SEQUENCE IF EXISTS seq_scriva_t_integrazione_istanza;
DROP SEQUENCE IF EXISTS seq_scriva_t_istanza;
DROP SEQUENCE IF EXISTS seq_scriva_t_notifica;
DROP SEQUENCE IF EXISTS seq_scriva_t_oggetto;
DROP SEQUENCE IF EXISTS seq_scriva_t_oggetto_istanza;
DROP SEQUENCE IF EXISTS seq_scriva_t_soggetto;
DROP SEQUENCE IF EXISTS seq_scriva_t_soggetto_istanza;
DROP SEQUENCE IF EXISTS seq_scriva_t_tentativo_pagamento;
