<?xml version="1.0" encoding="UTF-8"?>
<!-- ##################################################### -->
<!-- # Copyright Regione Piemonte - 2026                 # -->
<!-- # SPDX-License-Identifier: CC-BY-4.0                # -->
<!-- ##################################################### -->
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:vinq="../01_vocabularies/inquinamento"
    xmlns:epiir="../02_entities/progetto_impatto_inquinamento_rifiuti"
    targetNamespace="../02_entities/progetto_impatto_inquinamento_rifiuti"
    elementFormDefault="qualified" attributeFormDefault="qualified"
    version="1.0.0" xml:lang="it">

    <xsd:import namespace="../01_vocabularies/inquinamento"
        schemaLocation="../01_vocabularies/voc_inquinamento_v1.0.0.xsd" />

    <xsd:complexType name="progetto_impatto_inquinamento_rifiuti_ctype">
        <xsd:sequence>
            <xsd:element name="impatto_non_pertinente" type="xsd:boolean" minOccurs="1" maxOccurs="1" />
            <xsd:element name="fonte_inquinamento" minOccurs="0" maxOccurs="unbounded">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="tipo_fonte_inquinamento" type="vinq:inquinamento_voc" minOccurs="1" maxOccurs="1" />
                        <xsd:element name="desc_inquinamento" type="xsd:string" minOccurs="0" maxOccurs="1" />
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:element name="progetto_impatto_inquinamento_rifiuti" type="epiir:progetto_impatto_inquinamento_rifiuti_ctype" />
</xsd:schema>
