<?xml version="1.0" encoding="UTF-8"?>
<!-- ##################################################### -->
<!-- # Copyright Regione Piemonte - 2026                 # -->
<!-- # SPDX-License-Identifier: CC-BY-4.0                # -->
<!-- ##################################################### -->
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:esni="../02_entities/sito_natura_2000_interferito"
    xmlns:ccodelist="../commons/codelist"
    xmlns:canncl="../commons/xsdAnnotations"
    targetNamespace="../02_entities/sito_natura_2000_interferito"
    elementFormDefault="qualified" attributeFormDefault="qualified"
    version="1.0.0" xml:lang="it">

    <xsd:import namespace="../commons/codelist" schemaLocation="../commons-codelist.xsd"/>
    <xsd:import namespace="../commons/xsdAnnotations" schemaLocation="../commons-xsd-annotations.xsd"/>

    <xsd:simpleType name="numeric_5_stype">
        <xsd:restriction base="xsd:nonNegativeInteger">
            <xsd:maxInclusive value="99999" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:complexType name="sito_natura_2000_interferito_ctype">
        <xsd:sequence>
            <xsd:element name="codice_amministrativo_nome_sito_natura_2000_interferito" type="ccodelist:CodeType" minOccurs="1" maxOccurs="1" >
                <xsd:annotation>
                    <xsd:appinfo>
                        <canncl:codeListReference>
                            <canncl:ShortName>IT:SUAP:CL:SitiNatura2000</canncl:ShortName>
                        </canncl:codeListReference>
                    </xsd:appinfo>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="desc_discontinuita_barriere_infrastrutture_sito_natura_2000_interferito" minOccurs="0" maxOccurs="1">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:string">
                        <xsd:maxLength value="300"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
            <xsd:element name="distanza_sito_natura_2000_interferito" type="esni:numeric_5_stype" minOccurs="0" maxOccurs="1"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:element name="sito_natura_2000_interferito" type="esni:sito_natura_2000_interferito_ctype" />
</xsd:schema>
